package com.anytty.app

enum class AnyTTYDebugEvent {
    ACTIVITY_CREATED,
    ACTIVITY_RESUMED,
    ACTIVITY_PAUSED,
    ACTIVITY_DESTROYED,
    CONNECTION_PLUGIN_LOADED,
    GENERATION_CHANGE_FAILED,
    RESET_PAIRINGS_FAILED,
    BRIDGE_STARTED,
    NETWORK_CHANGED,
    WEBVIEW_UNSUPPORTED,
    WEBVIEW_RENDERER_UNRESPONSIVE,
    WEBVIEW_JAVASCRIPT_UNRESPONSIVE,
    WEBVIEW_RENDERER_GONE,
    FILE_SAVE_FAILED,
    PERSISTABLE_PERMISSION_FAILED,
    FILE_INFO_FAILED,
}
