// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: tui2/proto/tui2.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Limits struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MaxNodes            uint32                 `protobuf:"varint,1,opt,name=max_nodes,json=maxNodes,proto3" json:"max_nodes,omitempty"`
	MaxMessageBytes     uint32                 `protobuf:"varint,2,opt,name=max_message_bytes,json=maxMessageBytes,proto3" json:"max_message_bytes,omitempty"`
	MaxPasteBytes       uint32                 `protobuf:"varint,3,opt,name=max_paste_bytes,json=maxPasteBytes,proto3" json:"max_paste_bytes,omitempty"`
	MaxInflightRequests uint32                 `protobuf:"varint,4,opt,name=max_inflight_requests,json=maxInflightRequests,proto3" json:"max_inflight_requests,omitempty"`
	OwnerLeaseTtlMs     uint32                 `protobuf:"varint,5,opt,name=owner_lease_ttl_ms,json=ownerLeaseTtlMs,proto3" json:"owner_lease_ttl_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Limits) Reset() {
	*x = Limits{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Limits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Limits) ProtoMessage() {}

func (x *Limits) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Limits.ProtoReflect.Descriptor instead.
func (*Limits) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{0}
}

func (x *Limits) GetMaxNodes() uint32 {
	if x != nil {
		return x.MaxNodes
	}
	return 0
}

func (x *Limits) GetMaxMessageBytes() uint32 {
	if x != nil {
		return x.MaxMessageBytes
	}
	return 0
}

func (x *Limits) GetMaxPasteBytes() uint32 {
	if x != nil {
		return x.MaxPasteBytes
	}
	return 0
}

func (x *Limits) GetMaxInflightRequests() uint32 {
	if x != nil {
		return x.MaxInflightRequests
	}
	return 0
}

func (x *Limits) GetOwnerLeaseTtlMs() uint32 {
	if x != nil {
		return x.OwnerLeaseTtlMs
	}
	return 0
}

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        uint32                 `protobuf:"varint,1,opt,name=schema,proto3" json:"schema,omitempty"`
	ViewId        string                 `protobuf:"bytes,2,opt,name=view_id,json=viewId,proto3" json:"view_id,omitempty"`
	Epoch         uint64                 `protobuf:"varint,3,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Cols          uint32                 `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,5,opt,name=rows,proto3" json:"rows,omitempty"`
	Components    []string               `protobuf:"bytes,6,rep,name=components,proto3" json:"components,omitempty"`
	Events        []string               `protobuf:"bytes,7,rep,name=events,proto3" json:"events,omitempty"`
	Methods       []string               `protobuf:"bytes,8,rep,name=methods,proto3" json:"methods,omitempty"`
	Features      map[string]bool        `protobuf:"bytes,9,rep,name=features,proto3" json:"features,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Limits        *Limits                `protobuf:"bytes,10,opt,name=limits,proto3" json:"limits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetSchema() uint32 {
	if x != nil {
		return x.Schema
	}
	return 0
}

func (x *Hello) GetViewId() string {
	if x != nil {
		return x.ViewId
	}
	return ""
}

func (x *Hello) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Hello) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Hello) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Hello) GetComponents() []string {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *Hello) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Hello) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

func (x *Hello) GetFeatures() map[string]bool {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Hello) GetLimits() *Limits {
	if x != nil {
		return x.Limits
	}
	return nil
}

type Keys struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claim         []string               `protobuf:"bytes,1,rep,name=claim,proto3" json:"claim,omitempty"`
	All           bool                   `protobuf:"varint,2,opt,name=all,proto3" json:"all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Keys) Reset() {
	*x = Keys{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Keys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Keys) ProtoMessage() {}

func (x *Keys) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Keys.ProtoReflect.Descriptor instead.
func (*Keys) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{2}
}

func (x *Keys) GetClaim() []string {
	if x != nil {
		return x.Claim
	}
	return nil
}

func (x *Keys) GetAll() bool {
	if x != nil {
		return x.All
	}
	return false
}

type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         int32                  `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Flex          int32                  `protobuf:"varint,3,opt,name=flex,proto3" json:"flex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{3}
}

func (x *Size) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Size) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Size) GetFlex() int32 {
	if x != nil {
		return x.Flex
	}
	return 0
}

type Pos struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pos) Reset() {
	*x = Pos{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pos) ProtoMessage() {}

func (x *Pos) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pos.ProtoReflect.Descriptor instead.
func (*Pos) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{4}
}

func (x *Pos) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Pos) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Content struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Lines         []string               `protobuf:"bytes,2,rep,name=lines,proto3" json:"lines,omitempty"`
	Self          string                 `protobuf:"bytes,3,opt,name=self,proto3" json:"self,omitempty"`
	Props         map[string]string      `protobuf:"bytes,4,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Content) Reset() {
	*x = Content{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Content) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Content) ProtoMessage() {}

func (x *Content) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Content.ProtoReflect.Descriptor instead.
func (*Content) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{5}
}

func (x *Content) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Content) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

func (x *Content) GetSelf() string {
	if x != nil {
		return x.Self
	}
	return ""
}

func (x *Content) GetProps() map[string]string {
	if x != nil {
		return x.Props
	}
	return nil
}

type Cursor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col           int32                  `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Shape         string                 `protobuf:"bytes,3,opt,name=shape,proto3" json:"shape,omitempty"`
	Visible       *bool                  `protobuf:"varint,4,opt,name=visible,proto3,oneof" json:"visible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cursor) Reset() {
	*x = Cursor{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cursor) ProtoMessage() {}

func (x *Cursor) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cursor.ProtoReflect.Descriptor instead.
func (*Cursor) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{6}
}

func (x *Cursor) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Cursor) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *Cursor) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *Cursor) GetVisible() bool {
	if x != nil && x.Visible != nil {
		return *x.Visible
	}
	return false
}

type Box struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size          *Size                  `protobuf:"bytes,2,opt,name=size,proto3" json:"size,omitempty"`
	Pos           *Pos                   `protobuf:"bytes,3,opt,name=pos,proto3" json:"pos,omitempty"`
	Flow          string                 `protobuf:"bytes,4,opt,name=flow,proto3" json:"flow,omitempty"`
	Visible       *bool                  `protobuf:"varint,5,opt,name=visible,proto3,oneof" json:"visible,omitempty"`
	Cursor        *Cursor                `protobuf:"bytes,7,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Content       *Content               `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	Input         []string               `protobuf:"bytes,9,rep,name=input,proto3" json:"input,omitempty"`
	Focused       bool                   `protobuf:"varint,10,opt,name=focused,proto3" json:"focused,omitempty"`
	Children      []*Box                 `protobuf:"bytes,11,rep,name=children,proto3" json:"children,omitempty"`
	Style         string                 `protobuf:"bytes,12,opt,name=style,proto3" json:"style,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Box) Reset() {
	*x = Box{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Box) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Box) ProtoMessage() {}

func (x *Box) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Box.ProtoReflect.Descriptor instead.
func (*Box) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{7}
}

func (x *Box) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Box) GetSize() *Size {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *Box) GetPos() *Pos {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Box) GetFlow() string {
	if x != nil {
		return x.Flow
	}
	return ""
}

func (x *Box) GetVisible() bool {
	if x != nil && x.Visible != nil {
		return *x.Visible
	}
	return false
}

func (x *Box) GetCursor() *Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

func (x *Box) GetContent() *Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Box) GetInput() []string {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *Box) GetFocused() bool {
	if x != nil {
		return x.Focused
	}
	return false
}

func (x *Box) GetChildren() []*Box {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *Box) GetStyle() string {
	if x != nil {
		return x.Style
	}
	return ""
}

type View struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Rev           uint64                 `protobuf:"varint,2,opt,name=rev,proto3" json:"rev,omitempty"`
	Keys          *Keys                  `protobuf:"bytes,3,opt,name=keys,proto3" json:"keys,omitempty"`
	Root          *Box                   `protobuf:"bytes,4,opt,name=root,proto3" json:"root,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *View) Reset() {
	*x = View{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{8}
}

func (x *View) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *View) GetRev() uint64 {
	if x != nil {
		return x.Rev
	}
	return 0
}

func (x *View) GetKeys() *Keys {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *View) GetRoot() *Box {
	if x != nil {
		return x.Root
	}
	return nil
}

type Source struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind          string                 `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Endpoint      string                 `protobuf:"bytes,4,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	TerminalId    string                 `protobuf:"bytes,5,opt,name=terminal_id,json=terminalId,proto3" json:"terminal_id,omitempty"`
	Attached      bool                   `protobuf:"varint,6,opt,name=attached,proto3" json:"attached,omitempty"`
	Exited        bool                   `protobuf:"varint,7,opt,name=exited,proto3" json:"exited,omitempty"`
	ExitCode      int32                  `protobuf:"varint,8,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Health        string                 `protobuf:"bytes,9,opt,name=health,proto3" json:"health,omitempty"`
	ResizeOwner   string                 `protobuf:"bytes,10,opt,name=resize_owner,json=resizeOwner,proto3" json:"resize_owner,omitempty"`
	OwnerEpoch    uint64                 `protobuf:"varint,11,opt,name=owner_epoch,json=ownerEpoch,proto3" json:"owner_epoch,omitempty"`
	LastSeenMs    int64                  `protobuf:"varint,12,opt,name=last_seen_ms,json=lastSeenMs,proto3" json:"last_seen_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Source) Reset() {
	*x = Source{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Source) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Source) ProtoMessage() {}

func (x *Source) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Source.ProtoReflect.Descriptor instead.
func (*Source) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{9}
}

func (x *Source) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Source) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Source) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Source) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *Source) GetTerminalId() string {
	if x != nil {
		return x.TerminalId
	}
	return ""
}

func (x *Source) GetAttached() bool {
	if x != nil {
		return x.Attached
	}
	return false
}

func (x *Source) GetExited() bool {
	if x != nil {
		return x.Exited
	}
	return false
}

func (x *Source) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *Source) GetHealth() string {
	if x != nil {
		return x.Health
	}
	return ""
}

func (x *Source) GetResizeOwner() string {
	if x != nil {
		return x.ResizeOwner
	}
	return ""
}

func (x *Source) GetOwnerEpoch() uint64 {
	if x != nil {
		return x.OwnerEpoch
	}
	return 0
}

func (x *Source) GetLastSeenMs() int64 {
	if x != nil {
		return x.LastSeenMs
	}
	return 0
}

type SourcesEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Source              `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourcesEvent) Reset() {
	*x = SourcesEvent{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourcesEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourcesEvent) ProtoMessage() {}

func (x *SourcesEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourcesEvent.ProtoReflect.Descriptor instead.
func (*SourcesEvent) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{10}
}

func (x *SourcesEvent) GetItems() []*Source {
	if x != nil {
		return x.Items
	}
	return nil
}

type KeyEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Char          string                 `protobuf:"bytes,3,opt,name=char,proto3" json:"char,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyEvent) Reset() {
	*x = KeyEvent{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyEvent) ProtoMessage() {}

func (x *KeyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyEvent.ProtoReflect.Descriptor instead.
func (*KeyEvent) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{11}
}

func (x *KeyEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyEvent) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyEvent) GetChar() string {
	if x != nil {
		return x.Char
	}
	return ""
}

type PasteEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasteEvent) Reset() {
	*x = PasteEvent{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasteEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasteEvent) ProtoMessage() {}

func (x *PasteEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasteEvent.ProtoReflect.Descriptor instead.
func (*PasteEvent) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{12}
}

func (x *PasteEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PasteEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type MouseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Button        string                 `protobuf:"bytes,2,opt,name=button,proto3" json:"button,omitempty"`
	X             int32                  `protobuf:"varint,3,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,4,opt,name=y,proto3" json:"y,omitempty"`
	Node          string                 `protobuf:"bytes,5,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MouseEvent) Reset() {
	*x = MouseEvent{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MouseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MouseEvent) ProtoMessage() {}

func (x *MouseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MouseEvent.ProtoReflect.Descriptor instead.
func (*MouseEvent) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{13}
}

func (x *MouseEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MouseEvent) GetButton() string {
	if x != nil {
		return x.Button
	}
	return ""
}

func (x *MouseEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MouseEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MouseEvent) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type WheelEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Delta         int32                  `protobuf:"varint,1,opt,name=delta,proto3" json:"delta,omitempty"`
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	Node          string                 `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WheelEvent) Reset() {
	*x = WheelEvent{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WheelEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WheelEvent) ProtoMessage() {}

func (x *WheelEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WheelEvent.ProtoReflect.Descriptor instead.
func (*WheelEvent) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{14}
}

func (x *WheelEvent) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *WheelEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *WheelEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *WheelEvent) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

type ResizeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResizeEvent) Reset() {
	*x = ResizeEvent{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResizeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResizeEvent) ProtoMessage() {}

func (x *ResizeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResizeEvent.ProtoReflect.Descriptor instead.
func (*ResizeEvent) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{15}
}

func (x *ResizeEvent) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *ResizeEvent) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type NoticeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoticeEvent) Reset() {
	*x = NoticeEvent{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoticeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoticeEvent) ProtoMessage() {}

func (x *NoticeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoticeEvent.ProtoReflect.Descriptor instead.
func (*NoticeEvent) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{16}
}

func (x *NoticeEvent) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *NoticeEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ComponentEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Source        string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentEvent) Reset() {
	*x = ComponentEvent{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentEvent) ProtoMessage() {}

func (x *ComponentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentEvent.ProtoReflect.Descriptor instead.
func (*ComponentEvent) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{17}
}

func (x *ComponentEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ComponentEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ComponentEvent) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ViewRejectedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         uint64                 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Rev           uint64                 `protobuf:"varint,2,opt,name=rev,proto3" json:"rev,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewRejectedEvent) Reset() {
	*x = ViewRejectedEvent{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewRejectedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewRejectedEvent) ProtoMessage() {}

func (x *ViewRejectedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewRejectedEvent.ProtoReflect.Descriptor instead.
func (*ViewRejectedEvent) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{18}
}

func (x *ViewRejectedEvent) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *ViewRejectedEvent) GetRev() uint64 {
	if x != nil {
		return x.Rev
	}
	return 0
}

func (x *ViewRejectedEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*Event_Key
	//	*Event_Paste
	//	*Event_Mouse
	//	*Event_Wheel
	//	*Event_Resize
	//	*Event_Sources
	//	*Event_Notice
	//	*Event_Component
	//	*Event_ViewRejected
	Event         isEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{19}
}

func (x *Event) GetEvent() isEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Event) GetKey() *KeyEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_Key); ok {
			return x.Key
		}
	}
	return nil
}

func (x *Event) GetPaste() *PasteEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_Paste); ok {
			return x.Paste
		}
	}
	return nil
}

func (x *Event) GetMouse() *MouseEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_Mouse); ok {
			return x.Mouse
		}
	}
	return nil
}

func (x *Event) GetWheel() *WheelEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_Wheel); ok {
			return x.Wheel
		}
	}
	return nil
}

func (x *Event) GetResize() *ResizeEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *Event) GetSources() *SourcesEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_Sources); ok {
			return x.Sources
		}
	}
	return nil
}

func (x *Event) GetNotice() *NoticeEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_Notice); ok {
			return x.Notice
		}
	}
	return nil
}

func (x *Event) GetComponent() *ComponentEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_Component); ok {
			return x.Component
		}
	}
	return nil
}

func (x *Event) GetViewRejected() *ViewRejectedEvent {
	if x != nil {
		if x, ok := x.Event.(*Event_ViewRejected); ok {
			return x.ViewRejected
		}
	}
	return nil
}

type isEvent_Event interface {
	isEvent_Event()
}

type Event_Key struct {
	Key *KeyEvent `protobuf:"bytes,1,opt,name=key,proto3,oneof"`
}

type Event_Paste struct {
	Paste *PasteEvent `protobuf:"bytes,2,opt,name=paste,proto3,oneof"`
}

type Event_Mouse struct {
	Mouse *MouseEvent `protobuf:"bytes,3,opt,name=mouse,proto3,oneof"`
}

type Event_Wheel struct {
	Wheel *WheelEvent `protobuf:"bytes,4,opt,name=wheel,proto3,oneof"`
}

type Event_Resize struct {
	Resize *ResizeEvent `protobuf:"bytes,5,opt,name=resize,proto3,oneof"`
}

type Event_Sources struct {
	Sources *SourcesEvent `protobuf:"bytes,6,opt,name=sources,proto3,oneof"`
}

type Event_Notice struct {
	Notice *NoticeEvent `protobuf:"bytes,7,opt,name=notice,proto3,oneof"`
}

type Event_Component struct {
	Component *ComponentEvent `protobuf:"bytes,8,opt,name=component,proto3,oneof"`
}

type Event_ViewRejected struct {
	ViewRejected *ViewRejectedEvent `protobuf:"bytes,9,opt,name=view_rejected,json=viewRejected,proto3,oneof"`
}

func (*Event_Key) isEvent_Event() {}

func (*Event_Paste) isEvent_Event() {}

func (*Event_Mouse) isEvent_Event() {}

func (*Event_Wheel) isEvent_Event() {}

func (*Event_Resize) isEvent_Event() {}

func (*Event_Sources) isEvent_Event() {}

func (*Event_Notice) isEvent_Event() {}

func (*Event_Component) isEvent_Event() {}

func (*Event_ViewRejected) isEvent_Event() {}

type Selection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Start         int32                  `protobuf:"varint,2,opt,name=start,proto3" json:"start,omitempty"`
	End           int32                  `protobuf:"varint,3,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Selection) Reset() {
	*x = Selection{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Selection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Selection) ProtoMessage() {}

func (x *Selection) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Selection.ProtoReflect.Descriptor instead.
func (*Selection) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{20}
}

func (x *Selection) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Selection) GetStart() int32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *Selection) GetEnd() int32 {
	if x != nil {
		return x.End
	}
	return 0
}

type MethodParams struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Endpoint            string                 `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Id                  string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Fit                 *bool                  `protobuf:"varint,3,opt,name=fit,proto3,oneof" json:"fit,omitempty"`
	ExpectedOwnerEpoch  *uint64                `protobuf:"varint,4,opt,name=expected_owner_epoch,json=expectedOwnerEpoch,proto3,oneof" json:"expected_owner_epoch,omitempty"`
	Argv                []string               `protobuf:"bytes,5,rep,name=argv,proto3" json:"argv,omitempty"`
	Cwd                 string                 `protobuf:"bytes,6,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Env                 map[string]string      `protobuf:"bytes,7,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Title               string                 `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Ephemeral           *bool                  `protobuf:"varint,9,opt,name=ephemeral,proto3,oneof" json:"ephemeral,omitempty"`
	Delta               int32                  `protobuf:"varint,10,opt,name=delta,proto3" json:"delta,omitempty"`
	Sel                 *Selection             `protobuf:"bytes,11,opt,name=sel,proto3" json:"sel,omitempty"`
	Offset              int32                  `protobuf:"varint,12,opt,name=offset,proto3" json:"offset,omitempty"`
	Rows                int32                  `protobuf:"varint,13,opt,name=rows,proto3" json:"rows,omitempty"`
	EventId             string                 `protobuf:"bytes,14,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Source              string                 `protobuf:"bytes,15,opt,name=source,proto3" json:"source,omitempty"`
	CleanupOwned        *bool                  `protobuf:"varint,16,opt,name=cleanup_owned,json=cleanupOwned,proto3,oneof" json:"cleanup_owned,omitempty"`
	Kind                string                 `protobuf:"bytes,17,opt,name=kind,proto3" json:"kind,omitempty"`
	Socket              string                 `protobuf:"bytes,18,opt,name=socket,proto3" json:"socket,omitempty"`
	ConnectMode         string                 `protobuf:"bytes,19,opt,name=connect_mode,json=connectMode,proto3" json:"connect_mode,omitempty"`
	Address             string                 `protobuf:"bytes,20,opt,name=address,proto3" json:"address,omitempty"`
	SignalingAddresses  []string               `protobuf:"bytes,21,rep,name=signaling_addresses,json=signalingAddresses,proto3" json:"signaling_addresses,omitempty"`
	IceTcpAddresses     []string               `protobuf:"bytes,22,rep,name=ice_tcp_addresses,json=iceTcpAddresses,proto3" json:"ice_tcp_addresses,omitempty"`
	DaemonDeviceId      string                 `protobuf:"bytes,23,opt,name=daemon_device_id,json=daemonDeviceId,proto3" json:"daemon_device_id,omitempty"`
	DaemonFingerprint   string                 `protobuf:"bytes,24,opt,name=daemon_fingerprint,json=daemonFingerprint,proto3" json:"daemon_fingerprint,omitempty"`
	CredentialDir       string                 `protobuf:"bytes,25,opt,name=credential_dir,json=credentialDir,proto3" json:"credential_dir,omitempty"`
	CredentialRef       string                 `protobuf:"bytes,26,opt,name=credential_ref,json=credentialRef,proto3" json:"credential_ref,omitempty"`
	CloudGatewayAddress string                 `protobuf:"bytes,27,opt,name=cloud_gateway_address,json=cloudGatewayAddress,proto3" json:"cloud_gateway_address,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MethodParams) Reset() {
	*x = MethodParams{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodParams) ProtoMessage() {}

func (x *MethodParams) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodParams.ProtoReflect.Descriptor instead.
func (*MethodParams) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{21}
}

func (x *MethodParams) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *MethodParams) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MethodParams) GetFit() bool {
	if x != nil && x.Fit != nil {
		return *x.Fit
	}
	return false
}

func (x *MethodParams) GetExpectedOwnerEpoch() uint64 {
	if x != nil && x.ExpectedOwnerEpoch != nil {
		return *x.ExpectedOwnerEpoch
	}
	return 0
}

func (x *MethodParams) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *MethodParams) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *MethodParams) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *MethodParams) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MethodParams) GetEphemeral() bool {
	if x != nil && x.Ephemeral != nil {
		return *x.Ephemeral
	}
	return false
}

func (x *MethodParams) GetDelta() int32 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *MethodParams) GetSel() *Selection {
	if x != nil {
		return x.Sel
	}
	return nil
}

func (x *MethodParams) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MethodParams) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *MethodParams) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *MethodParams) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *MethodParams) GetCleanupOwned() bool {
	if x != nil && x.CleanupOwned != nil {
		return *x.CleanupOwned
	}
	return false
}

func (x *MethodParams) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MethodParams) GetSocket() string {
	if x != nil {
		return x.Socket
	}
	return ""
}

func (x *MethodParams) GetConnectMode() string {
	if x != nil {
		return x.ConnectMode
	}
	return ""
}

func (x *MethodParams) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MethodParams) GetSignalingAddresses() []string {
	if x != nil {
		return x.SignalingAddresses
	}
	return nil
}

func (x *MethodParams) GetIceTcpAddresses() []string {
	if x != nil {
		return x.IceTcpAddresses
	}
	return nil
}

func (x *MethodParams) GetDaemonDeviceId() string {
	if x != nil {
		return x.DaemonDeviceId
	}
	return ""
}

func (x *MethodParams) GetDaemonFingerprint() string {
	if x != nil {
		return x.DaemonFingerprint
	}
	return ""
}

func (x *MethodParams) GetCredentialDir() string {
	if x != nil {
		return x.CredentialDir
	}
	return ""
}

func (x *MethodParams) GetCredentialRef() string {
	if x != nil {
		return x.CredentialRef
	}
	return ""
}

func (x *MethodParams) GetCloudGatewayAddress() string {
	if x != nil {
		return x.CloudGatewayAddress
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Method        string                 `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Params        *MethodParams          `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{22}
}

func (x *Result) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Result) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Result) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Result) GetParams() *MethodParams {
	if x != nil {
		return x.Params
	}
	return nil
}

type MethodData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []string               `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Endpoint      string                 `protobuf:"bytes,3,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MethodData) Reset() {
	*x = MethodData{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MethodData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodData) ProtoMessage() {}

func (x *MethodData) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodData.ProtoReflect.Descriptor instead.
func (*MethodData) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{23}
}

func (x *MethodData) GetRows() []string {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *MethodData) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MethodData) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *MethodData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint64                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Data          *MethodData            `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_tui2_proto_tui2_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_tui2_proto_tui2_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_tui2_proto_tui2_proto_rawDescGZIP(), []int{24}
}

func (x *Response) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *Response) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Response) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Response) GetData() *MethodData {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_tui2_proto_tui2_proto protoreflect.FileDescriptor

const file_tui2_proto_tui2_proto_rawDesc = "" +
	"\n" +
	"\x15tui2/proto/tui2.proto\x12\x0eanytty.tui2.v1\"\xda\x01\n" +
	"\x06Limits\x12\x1b\n" +
	"\tmax_nodes\x18\x01 \x01(\rR\bmaxNodes\x12*\n" +
	"\x11max_message_bytes\x18\x02 \x01(\rR\x0fmaxMessageBytes\x12&\n" +
	"\x0fmax_paste_bytes\x18\x03 \x01(\rR\rmaxPasteBytes\x122\n" +
	"\x15max_inflight_requests\x18\x04 \x01(\rR\x13maxInflightRequests\x12+\n" +
	"\x12owner_lease_ttl_ms\x18\x05 \x01(\rR\x0fownerLeaseTtlMs\"\xf6\x02\n" +
	"\x05Hello\x12\x16\n" +
	"\x06schema\x18\x01 \x01(\rR\x06schema\x12\x17\n" +
	"\aview_id\x18\x02 \x01(\tR\x06viewId\x12\x14\n" +
	"\x05epoch\x18\x03 \x01(\x04R\x05epoch\x12\x12\n" +
	"\x04cols\x18\x04 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x05 \x01(\rR\x04rows\x12\x1e\n" +
	"\n" +
	"components\x18\x06 \x03(\tR\n" +
	"components\x12\x16\n" +
	"\x06events\x18\a \x03(\tR\x06events\x12\x18\n" +
	"\amethods\x18\b \x03(\tR\amethods\x12?\n" +
	"\bfeatures\x18\t \x03(\v2#.anytty.tui2.v1.Hello.FeaturesEntryR\bfeatures\x12.\n" +
	"\x06limits\x18\n" +
	" \x01(\v2\x16.anytty.tui2.v1.LimitsR\x06limits\x1a;\n" +
	"\rFeaturesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\".\n" +
	"\x04Keys\x12\x14\n" +
	"\x05claim\x18\x01 \x03(\tR\x05claim\x12\x10\n" +
	"\x03all\x18\x02 \x01(\bR\x03all\"H\n" +
	"\x04Size\x12\x14\n" +
	"\x05width\x18\x01 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\x05R\x06height\x12\x12\n" +
	"\x04flex\x18\x03 \x01(\x05R\x04flex\"!\n" +
	"\x03Pos\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\xbb\x01\n" +
	"\aContent\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x14\n" +
	"\x05lines\x18\x02 \x03(\tR\x05lines\x12\x12\n" +
	"\x04self\x18\x03 \x01(\tR\x04self\x128\n" +
	"\x05props\x18\x04 \x03(\v2\".anytty.tui2.v1.Content.PropsEntryR\x05props\x1a8\n" +
	"\n" +
	"PropsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"m\n" +
	"\x06Cursor\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x02 \x01(\x05R\x03col\x12\x14\n" +
	"\x05shape\x18\x03 \x01(\tR\x05shape\x12\x1d\n" +
	"\avisible\x18\x04 \x01(\bH\x00R\avisible\x88\x01\x01B\n" +
	"\n" +
	"\b_visible\"\x8d\x03\n" +
	"\x03Box\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12(\n" +
	"\x04size\x18\x02 \x01(\v2\x14.anytty.tui2.v1.SizeR\x04size\x12%\n" +
	"\x03pos\x18\x03 \x01(\v2\x13.anytty.tui2.v1.PosR\x03pos\x12\x12\n" +
	"\x04flow\x18\x04 \x01(\tR\x04flow\x12\x1d\n" +
	"\avisible\x18\x05 \x01(\bH\x00R\avisible\x88\x01\x01\x12.\n" +
	"\x06cursor\x18\a \x01(\v2\x16.anytty.tui2.v1.CursorR\x06cursor\x121\n" +
	"\acontent\x18\b \x01(\v2\x17.anytty.tui2.v1.ContentR\acontent\x12\x14\n" +
	"\x05input\x18\t \x03(\tR\x05input\x12\x18\n" +
	"\afocused\x18\n" +
	" \x01(\bR\afocused\x12/\n" +
	"\bchildren\x18\v \x03(\v2\x13.anytty.tui2.v1.BoxR\bchildren\x12\x14\n" +
	"\x05style\x18\f \x01(\tR\x05styleB\n" +
	"\n" +
	"\b_visibleJ\x04\b\x06\x10\aR\x06border\"\x81\x01\n" +
	"\x04View\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x10\n" +
	"\x03rev\x18\x02 \x01(\x04R\x03rev\x12(\n" +
	"\x04keys\x18\x03 \x01(\v2\x14.anytty.tui2.v1.KeysR\x04keys\x12'\n" +
	"\x04root\x18\x04 \x01(\v2\x13.anytty.tui2.v1.BoxR\x04root\"\xce\x02\n" +
	"\x06Source\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bendpoint\x18\x04 \x01(\tR\bendpoint\x12\x1f\n" +
	"\vterminal_id\x18\x05 \x01(\tR\n" +
	"terminalId\x12\x1a\n" +
	"\battached\x18\x06 \x01(\bR\battached\x12\x16\n" +
	"\x06exited\x18\a \x01(\bR\x06exited\x12\x1b\n" +
	"\texit_code\x18\b \x01(\x05R\bexitCode\x12\x16\n" +
	"\x06health\x18\t \x01(\tR\x06health\x12!\n" +
	"\fresize_owner\x18\n" +
	" \x01(\tR\vresizeOwner\x12\x1f\n" +
	"\vowner_epoch\x18\v \x01(\x04R\n" +
	"ownerEpoch\x12 \n" +
	"\flast_seen_ms\x18\f \x01(\x03R\n" +
	"lastSeenMs\"<\n" +
	"\fSourcesEvent\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.anytty.tui2.v1.SourceR\x05items\"@\n" +
	"\bKeyEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x12\n" +
	"\x04char\x18\x03 \x01(\tR\x04char\"0\n" +
	"\n" +
	"PasteEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"l\n" +
	"\n" +
	"MouseEvent\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06button\x18\x02 \x01(\tR\x06button\x12\f\n" +
	"\x01x\x18\x03 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x05R\x01y\x12\x12\n" +
	"\x04node\x18\x05 \x01(\tR\x04node\"R\n" +
	"\n" +
	"WheelEvent\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\x05R\x05delta\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12\x12\n" +
	"\x04node\x18\x04 \x01(\tR\x04node\"5\n" +
	"\vResizeEvent\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"=\n" +
	"\vNoticeEvent\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"R\n" +
	"\x0eComponentEvent\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"S\n" +
	"\x11ViewRejectedEvent\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x04R\x05epoch\x12\x10\n" +
	"\x03rev\x18\x02 \x01(\x04R\x03rev\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"\x8c\x04\n" +
	"\x05Event\x12,\n" +
	"\x03key\x18\x01 \x01(\v2\x18.anytty.tui2.v1.KeyEventH\x00R\x03key\x122\n" +
	"\x05paste\x18\x02 \x01(\v2\x1a.anytty.tui2.v1.PasteEventH\x00R\x05paste\x122\n" +
	"\x05mouse\x18\x03 \x01(\v2\x1a.anytty.tui2.v1.MouseEventH\x00R\x05mouse\x122\n" +
	"\x05wheel\x18\x04 \x01(\v2\x1a.anytty.tui2.v1.WheelEventH\x00R\x05wheel\x125\n" +
	"\x06resize\x18\x05 \x01(\v2\x1b.anytty.tui2.v1.ResizeEventH\x00R\x06resize\x128\n" +
	"\asources\x18\x06 \x01(\v2\x1c.anytty.tui2.v1.SourcesEventH\x00R\asources\x125\n" +
	"\x06notice\x18\a \x01(\v2\x1b.anytty.tui2.v1.NoticeEventH\x00R\x06notice\x12>\n" +
	"\tcomponent\x18\b \x01(\v2\x1e.anytty.tui2.v1.ComponentEventH\x00R\tcomponent\x12H\n" +
	"\rview_rejected\x18\t \x01(\v2!.anytty.tui2.v1.ViewRejectedEventH\x00R\fviewRejectedB\a\n" +
	"\x05event\"G\n" +
	"\tSelection\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x14\n" +
	"\x05start\x18\x02 \x01(\x05R\x05start\x12\x10\n" +
	"\x03end\x18\x03 \x01(\x05R\x03end\"\x86\b\n" +
	"\fMethodParams\x12\x1a\n" +
	"\bendpoint\x18\x01 \x01(\tR\bendpoint\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x15\n" +
	"\x03fit\x18\x03 \x01(\bH\x00R\x03fit\x88\x01\x01\x125\n" +
	"\x14expected_owner_epoch\x18\x04 \x01(\x04H\x01R\x12expectedOwnerEpoch\x88\x01\x01\x12\x12\n" +
	"\x04argv\x18\x05 \x03(\tR\x04argv\x12\x10\n" +
	"\x03cwd\x18\x06 \x01(\tR\x03cwd\x127\n" +
	"\x03env\x18\a \x03(\v2%.anytty.tui2.v1.MethodParams.EnvEntryR\x03env\x12\x14\n" +
	"\x05title\x18\b \x01(\tR\x05title\x12!\n" +
	"\tephemeral\x18\t \x01(\bH\x02R\tephemeral\x88\x01\x01\x12\x14\n" +
	"\x05delta\x18\n" +
	" \x01(\x05R\x05delta\x12+\n" +
	"\x03sel\x18\v \x01(\v2\x19.anytty.tui2.v1.SelectionR\x03sel\x12\x16\n" +
	"\x06offset\x18\f \x01(\x05R\x06offset\x12\x12\n" +
	"\x04rows\x18\r \x01(\x05R\x04rows\x12\x19\n" +
	"\bevent_id\x18\x0e \x01(\tR\aeventId\x12\x16\n" +
	"\x06source\x18\x0f \x01(\tR\x06source\x12(\n" +
	"\rcleanup_owned\x18\x10 \x01(\bH\x03R\fcleanupOwned\x88\x01\x01\x12\x12\n" +
	"\x04kind\x18\x11 \x01(\tR\x04kind\x12\x16\n" +
	"\x06socket\x18\x12 \x01(\tR\x06socket\x12!\n" +
	"\fconnect_mode\x18\x13 \x01(\tR\vconnectMode\x12\x18\n" +
	"\aaddress\x18\x14 \x01(\tR\aaddress\x12/\n" +
	"\x13signaling_addresses\x18\x15 \x03(\tR\x12signalingAddresses\x12*\n" +
	"\x11ice_tcp_addresses\x18\x16 \x03(\tR\x0ficeTcpAddresses\x12(\n" +
	"\x10daemon_device_id\x18\x17 \x01(\tR\x0edaemonDeviceId\x12-\n" +
	"\x12daemon_fingerprint\x18\x18 \x01(\tR\x11daemonFingerprint\x12%\n" +
	"\x0ecredential_dir\x18\x19 \x01(\tR\rcredentialDir\x12%\n" +
	"\x0ecredential_ref\x18\x1a \x01(\tR\rcredentialRef\x122\n" +
	"\x15cloud_gateway_address\x18\x1b \x01(\tR\x13cloudGatewayAddress\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04_fitB\x17\n" +
	"\x15_expected_owner_epochB\f\n" +
	"\n" +
	"_ephemeralB\x10\n" +
	"\x0e_cleanup_owned\"\x8b\x01\n" +
	"\x06Result\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x16\n" +
	"\x06method\x18\x03 \x01(\tR\x06method\x124\n" +
	"\x06params\x18\x04 \x01(\v2\x1c.anytty.tui2.v1.MethodParamsR\x06params\"`\n" +
	"\n" +
	"MethodData\x12\x12\n" +
	"\x04rows\x18\x01 \x03(\tR\x04rows\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x1a\n" +
	"\bendpoint\x18\x03 \x01(\tR\bendpoint\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\"\x95\x01\n" +
	"\bResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epoch\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12.\n" +
	"\x04data\x18\x04 \x01(\v2\x1a.anytty.tui2.v1.MethodDataR\x04data\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05errorB1Z/github.com/anytty/anytty/tui2/protobuf;protobufb\x06proto3"

var (
	file_tui2_proto_tui2_proto_rawDescOnce sync.Once
	file_tui2_proto_tui2_proto_rawDescData []byte
)

func file_tui2_proto_tui2_proto_rawDescGZIP() []byte {
	file_tui2_proto_tui2_proto_rawDescOnce.Do(func() {
		file_tui2_proto_tui2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tui2_proto_tui2_proto_rawDesc), len(file_tui2_proto_tui2_proto_rawDesc)))
	})
	return file_tui2_proto_tui2_proto_rawDescData
}

var file_tui2_proto_tui2_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_tui2_proto_tui2_proto_goTypes = []any{
	(*Limits)(nil),            // 0: anytty.tui2.v1.Limits
	(*Hello)(nil),             // 1: anytty.tui2.v1.Hello
	(*Keys)(nil),              // 2: anytty.tui2.v1.Keys
	(*Size)(nil),              // 3: anytty.tui2.v1.Size
	(*Pos)(nil),               // 4: anytty.tui2.v1.Pos
	(*Content)(nil),           // 5: anytty.tui2.v1.Content
	(*Cursor)(nil),            // 6: anytty.tui2.v1.Cursor
	(*Box)(nil),               // 7: anytty.tui2.v1.Box
	(*View)(nil),              // 8: anytty.tui2.v1.View
	(*Source)(nil),            // 9: anytty.tui2.v1.Source
	(*SourcesEvent)(nil),      // 10: anytty.tui2.v1.SourcesEvent
	(*KeyEvent)(nil),          // 11: anytty.tui2.v1.KeyEvent
	(*PasteEvent)(nil),        // 12: anytty.tui2.v1.PasteEvent
	(*MouseEvent)(nil),        // 13: anytty.tui2.v1.MouseEvent
	(*WheelEvent)(nil),        // 14: anytty.tui2.v1.WheelEvent
	(*ResizeEvent)(nil),       // 15: anytty.tui2.v1.ResizeEvent
	(*NoticeEvent)(nil),       // 16: anytty.tui2.v1.NoticeEvent
	(*ComponentEvent)(nil),    // 17: anytty.tui2.v1.ComponentEvent
	(*ViewRejectedEvent)(nil), // 18: anytty.tui2.v1.ViewRejectedEvent
	(*Event)(nil),             // 19: anytty.tui2.v1.Event
	(*Selection)(nil),         // 20: anytty.tui2.v1.Selection
	(*MethodParams)(nil),      // 21: anytty.tui2.v1.MethodParams
	(*Result)(nil),            // 22: anytty.tui2.v1.Result
	(*MethodData)(nil),        // 23: anytty.tui2.v1.MethodData
	(*Response)(nil),          // 24: anytty.tui2.v1.Response
	nil,                       // 25: anytty.tui2.v1.Hello.FeaturesEntry
	nil,                       // 26: anytty.tui2.v1.Content.PropsEntry
	nil,                       // 27: anytty.tui2.v1.MethodParams.EnvEntry
}
var file_tui2_proto_tui2_proto_depIdxs = []int32{
	25, // 0: anytty.tui2.v1.Hello.features:type_name -> anytty.tui2.v1.Hello.FeaturesEntry
	0,  // 1: anytty.tui2.v1.Hello.limits:type_name -> anytty.tui2.v1.Limits
	26, // 2: anytty.tui2.v1.Content.props:type_name -> anytty.tui2.v1.Content.PropsEntry
	3,  // 3: anytty.tui2.v1.Box.size:type_name -> anytty.tui2.v1.Size
	4,  // 4: anytty.tui2.v1.Box.pos:type_name -> anytty.tui2.v1.Pos
	6,  // 5: anytty.tui2.v1.Box.cursor:type_name -> anytty.tui2.v1.Cursor
	5,  // 6: anytty.tui2.v1.Box.content:type_name -> anytty.tui2.v1.Content
	7,  // 7: anytty.tui2.v1.Box.children:type_name -> anytty.tui2.v1.Box
	2,  // 8: anytty.tui2.v1.View.keys:type_name -> anytty.tui2.v1.Keys
	7,  // 9: anytty.tui2.v1.View.root:type_name -> anytty.tui2.v1.Box
	9,  // 10: anytty.tui2.v1.SourcesEvent.items:type_name -> anytty.tui2.v1.Source
	11, // 11: anytty.tui2.v1.Event.key:type_name -> anytty.tui2.v1.KeyEvent
	12, // 12: anytty.tui2.v1.Event.paste:type_name -> anytty.tui2.v1.PasteEvent
	13, // 13: anytty.tui2.v1.Event.mouse:type_name -> anytty.tui2.v1.MouseEvent
	14, // 14: anytty.tui2.v1.Event.wheel:type_name -> anytty.tui2.v1.WheelEvent
	15, // 15: anytty.tui2.v1.Event.resize:type_name -> anytty.tui2.v1.ResizeEvent
	10, // 16: anytty.tui2.v1.Event.sources:type_name -> anytty.tui2.v1.SourcesEvent
	16, // 17: anytty.tui2.v1.Event.notice:type_name -> anytty.tui2.v1.NoticeEvent
	17, // 18: anytty.tui2.v1.Event.component:type_name -> anytty.tui2.v1.ComponentEvent
	18, // 19: anytty.tui2.v1.Event.view_rejected:type_name -> anytty.tui2.v1.ViewRejectedEvent
	27, // 20: anytty.tui2.v1.MethodParams.env:type_name -> anytty.tui2.v1.MethodParams.EnvEntry
	20, // 21: anytty.tui2.v1.MethodParams.sel:type_name -> anytty.tui2.v1.Selection
	21, // 22: anytty.tui2.v1.Result.params:type_name -> anytty.tui2.v1.MethodParams
	23, // 23: anytty.tui2.v1.Response.data:type_name -> anytty.tui2.v1.MethodData
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_tui2_proto_tui2_proto_init() }
func file_tui2_proto_tui2_proto_init() {
	if File_tui2_proto_tui2_proto != nil {
		return
	}
	file_tui2_proto_tui2_proto_msgTypes[6].OneofWrappers = []any{}
	file_tui2_proto_tui2_proto_msgTypes[7].OneofWrappers = []any{}
	file_tui2_proto_tui2_proto_msgTypes[19].OneofWrappers = []any{
		(*Event_Key)(nil),
		(*Event_Paste)(nil),
		(*Event_Mouse)(nil),
		(*Event_Wheel)(nil),
		(*Event_Resize)(nil),
		(*Event_Sources)(nil),
		(*Event_Notice)(nil),
		(*Event_Component)(nil),
		(*Event_ViewRejected)(nil),
	}
	file_tui2_proto_tui2_proto_msgTypes[21].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tui2_proto_tui2_proto_rawDesc), len(file_tui2_proto_tui2_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tui2_proto_tui2_proto_goTypes,
		DependencyIndexes: file_tui2_proto_tui2_proto_depIdxs,
		MessageInfos:      file_tui2_proto_tui2_proto_msgTypes,
	}.Build()
	File_tui2_proto_tui2_proto = out.File
	file_tui2_proto_tui2_proto_goTypes = nil
	file_tui2_proto_tui2_proto_depIdxs = nil
}
