// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cloud/v1/certificate.proto

package cloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EdgePublicCertificateStatus is the current automatically managed TLS
// credential presented by an Edge public endpoint. Private key material never
// leaves the Edge and is never part of this projection.
type EdgePublicCertificateStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicEndpoint    string                 `protobuf:"bytes,1,opt,name=public_endpoint,json=publicEndpoint,proto3" json:"public_endpoint,omitempty"`
	CertificateSha256 []byte                 `protobuf:"bytes,2,opt,name=certificate_sha256,json=certificateSha256,proto3" json:"certificate_sha256,omitempty"`
	NotBefore         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	RenewalPending    bool                   `protobuf:"varint,5,opt,name=renewal_pending,json=renewalPending,proto3" json:"renewal_pending,omitempty"`
	LastErrorCode     string                 `protobuf:"bytes,6,opt,name=last_error_code,json=lastErrorCode,proto3" json:"last_error_code,omitempty"`
	LastErrorMessage  string                 `protobuf:"bytes,7,opt,name=last_error_message,json=lastErrorMessage,proto3" json:"last_error_message,omitempty"`
	LastAttemptAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_attempt_at,json=lastAttemptAt,proto3" json:"last_attempt_at,omitempty"`
	AppliedAt         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EdgePublicCertificateStatus) Reset() {
	*x = EdgePublicCertificateStatus{}
	mi := &file_cloud_v1_certificate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgePublicCertificateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgePublicCertificateStatus) ProtoMessage() {}

func (x *EdgePublicCertificateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_certificate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgePublicCertificateStatus.ProtoReflect.Descriptor instead.
func (*EdgePublicCertificateStatus) Descriptor() ([]byte, []int) {
	return file_cloud_v1_certificate_proto_rawDescGZIP(), []int{0}
}

func (x *EdgePublicCertificateStatus) GetPublicEndpoint() string {
	if x != nil {
		return x.PublicEndpoint
	}
	return ""
}

func (x *EdgePublicCertificateStatus) GetCertificateSha256() []byte {
	if x != nil {
		return x.CertificateSha256
	}
	return nil
}

func (x *EdgePublicCertificateStatus) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *EdgePublicCertificateStatus) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

func (x *EdgePublicCertificateStatus) GetRenewalPending() bool {
	if x != nil {
		return x.RenewalPending
	}
	return false
}

func (x *EdgePublicCertificateStatus) GetLastErrorCode() string {
	if x != nil {
		return x.LastErrorCode
	}
	return ""
}

func (x *EdgePublicCertificateStatus) GetLastErrorMessage() string {
	if x != nil {
		return x.LastErrorMessage
	}
	return ""
}

func (x *EdgePublicCertificateStatus) GetLastAttemptAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastAttemptAt
	}
	return nil
}

func (x *EdgePublicCertificateStatus) GetAppliedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.AppliedAt
	}
	return nil
}

// EdgePublicCertificateRenewRequest is sent only inside an authenticated
// EdgeControl stream. The new private key is generated and retained by Edge.
type EdgePublicCertificateRenewRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RequestId                string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CsrPem                   []byte                 `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	CurrentCertificateSha256 []byte                 `protobuf:"bytes,3,opt,name=current_certificate_sha256,json=currentCertificateSha256,proto3" json:"current_certificate_sha256,omitempty"`
	RequestedAt              *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=requested_at,json=requestedAt,proto3" json:"requested_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *EdgePublicCertificateRenewRequest) Reset() {
	*x = EdgePublicCertificateRenewRequest{}
	mi := &file_cloud_v1_certificate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgePublicCertificateRenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgePublicCertificateRenewRequest) ProtoMessage() {}

func (x *EdgePublicCertificateRenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_certificate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgePublicCertificateRenewRequest.ProtoReflect.Descriptor instead.
func (*EdgePublicCertificateRenewRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_certificate_proto_rawDescGZIP(), []int{1}
}

func (x *EdgePublicCertificateRenewRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EdgePublicCertificateRenewRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

func (x *EdgePublicCertificateRenewRequest) GetCurrentCertificateSha256() []byte {
	if x != nil {
		return x.CurrentCertificateSha256
	}
	return nil
}

func (x *EdgePublicCertificateRenewRequest) GetRequestedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RequestedAt
	}
	return nil
}

// EdgePublicCertificateRenewResponse contains a serverAuth chain signed for
// the Controller-owned public_endpoint of the authenticated Edge.
type EdgePublicCertificateRenewResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RequestId         string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CertificatePem    []byte                 `protobuf:"bytes,2,opt,name=certificate_pem,json=certificatePem,proto3" json:"certificate_pem,omitempty"`
	CertificateSha256 []byte                 `protobuf:"bytes,3,opt,name=certificate_sha256,json=certificateSha256,proto3" json:"certificate_sha256,omitempty"`
	NotBefore         *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=not_before,json=notBefore,proto3" json:"not_before,omitempty"`
	NotAfter          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=not_after,json=notAfter,proto3" json:"not_after,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *EdgePublicCertificateRenewResponse) Reset() {
	*x = EdgePublicCertificateRenewResponse{}
	mi := &file_cloud_v1_certificate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgePublicCertificateRenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgePublicCertificateRenewResponse) ProtoMessage() {}

func (x *EdgePublicCertificateRenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_certificate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgePublicCertificateRenewResponse.ProtoReflect.Descriptor instead.
func (*EdgePublicCertificateRenewResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_certificate_proto_rawDescGZIP(), []int{2}
}

func (x *EdgePublicCertificateRenewResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EdgePublicCertificateRenewResponse) GetCertificatePem() []byte {
	if x != nil {
		return x.CertificatePem
	}
	return nil
}

func (x *EdgePublicCertificateRenewResponse) GetCertificateSha256() []byte {
	if x != nil {
		return x.CertificateSha256
	}
	return nil
}

func (x *EdgePublicCertificateRenewResponse) GetNotBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.NotBefore
	}
	return nil
}

func (x *EdgePublicCertificateRenewResponse) GetNotAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.NotAfter
	}
	return nil
}

// EdgePublicCertificateApplied reports atomic persistence and TLS hot reload.
// A failed application leaves the previously loaded credential untouched.
type EdgePublicCertificateApplied struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	RequestId     string                       `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        *EdgePublicCertificateStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Applied       bool                         `protobuf:"varint,3,opt,name=applied,proto3" json:"applied,omitempty"`
	ErrorCode     string                       `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                       `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgePublicCertificateApplied) Reset() {
	*x = EdgePublicCertificateApplied{}
	mi := &file_cloud_v1_certificate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgePublicCertificateApplied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgePublicCertificateApplied) ProtoMessage() {}

func (x *EdgePublicCertificateApplied) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_certificate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgePublicCertificateApplied.ProtoReflect.Descriptor instead.
func (*EdgePublicCertificateApplied) Descriptor() ([]byte, []int) {
	return file_cloud_v1_certificate_proto_rawDescGZIP(), []int{3}
}

func (x *EdgePublicCertificateApplied) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *EdgePublicCertificateApplied) GetStatus() *EdgePublicCertificateStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *EdgePublicCertificateApplied) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *EdgePublicCertificateApplied) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *EdgePublicCertificateApplied) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_cloud_v1_certificate_proto protoreflect.FileDescriptor

const file_cloud_v1_certificate_proto_rawDesc = "" +
	"\n" +
	"\x1acloud/v1/certificate.proto\x12\x0fanytty.cloud.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe7\x03\n" +
	"\x1bEdgePublicCertificateStatus\x12'\n" +
	"\x0fpublic_endpoint\x18\x01 \x01(\tR\x0epublicEndpoint\x12-\n" +
	"\x12certificate_sha256\x18\x02 \x01(\fR\x11certificateSha256\x129\n" +
	"\n" +
	"not_before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\x12'\n" +
	"\x0frenewal_pending\x18\x05 \x01(\bR\x0erenewalPending\x12&\n" +
	"\x0flast_error_code\x18\x06 \x01(\tR\rlastErrorCode\x12,\n" +
	"\x12last_error_message\x18\a \x01(\tR\x10lastErrorMessage\x12B\n" +
	"\x0flast_attempt_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\rlastAttemptAt\x129\n" +
	"\n" +
	"applied_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tappliedAt\"\xd8\x01\n" +
	"!EdgePublicCertificateRenewRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\fR\x06csrPem\x12<\n" +
	"\x1acurrent_certificate_sha256\x18\x03 \x01(\fR\x18currentCertificateSha256\x12=\n" +
	"\frequested_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\vrequestedAt\"\x8f\x02\n" +
	"\"EdgePublicCertificateRenewResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12'\n" +
	"\x0fcertificate_pem\x18\x02 \x01(\fR\x0ecertificatePem\x12-\n" +
	"\x12certificate_sha256\x18\x03 \x01(\fR\x11certificateSha256\x129\n" +
	"\n" +
	"not_before\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tnotBefore\x127\n" +
	"\tnot_after\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bnotAfter\"\xe1\x01\n" +
	"\x1cEdgePublicCertificateApplied\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12D\n" +
	"\x06status\x18\x02 \x01(\v2,.anytty.cloud.v1.EdgePublicCertificateStatusR\x06status\x12\x18\n" +
	"\aapplied\x18\x03 \x01(\bR\aapplied\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessageB1Z/github.com/anytty/anytty/proto/cloud/v1;cloudv1b\x06proto3"

var (
	file_cloud_v1_certificate_proto_rawDescOnce sync.Once
	file_cloud_v1_certificate_proto_rawDescData []byte
)

func file_cloud_v1_certificate_proto_rawDescGZIP() []byte {
	file_cloud_v1_certificate_proto_rawDescOnce.Do(func() {
		file_cloud_v1_certificate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_v1_certificate_proto_rawDesc), len(file_cloud_v1_certificate_proto_rawDesc)))
	})
	return file_cloud_v1_certificate_proto_rawDescData
}

var file_cloud_v1_certificate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cloud_v1_certificate_proto_goTypes = []any{
	(*EdgePublicCertificateStatus)(nil),        // 0: anytty.cloud.v1.EdgePublicCertificateStatus
	(*EdgePublicCertificateRenewRequest)(nil),  // 1: anytty.cloud.v1.EdgePublicCertificateRenewRequest
	(*EdgePublicCertificateRenewResponse)(nil), // 2: anytty.cloud.v1.EdgePublicCertificateRenewResponse
	(*EdgePublicCertificateApplied)(nil),       // 3: anytty.cloud.v1.EdgePublicCertificateApplied
	(*timestamppb.Timestamp)(nil),              // 4: google.protobuf.Timestamp
}
var file_cloud_v1_certificate_proto_depIdxs = []int32{
	4, // 0: anytty.cloud.v1.EdgePublicCertificateStatus.not_before:type_name -> google.protobuf.Timestamp
	4, // 1: anytty.cloud.v1.EdgePublicCertificateStatus.not_after:type_name -> google.protobuf.Timestamp
	4, // 2: anytty.cloud.v1.EdgePublicCertificateStatus.last_attempt_at:type_name -> google.protobuf.Timestamp
	4, // 3: anytty.cloud.v1.EdgePublicCertificateStatus.applied_at:type_name -> google.protobuf.Timestamp
	4, // 4: anytty.cloud.v1.EdgePublicCertificateRenewRequest.requested_at:type_name -> google.protobuf.Timestamp
	4, // 5: anytty.cloud.v1.EdgePublicCertificateRenewResponse.not_before:type_name -> google.protobuf.Timestamp
	4, // 6: anytty.cloud.v1.EdgePublicCertificateRenewResponse.not_after:type_name -> google.protobuf.Timestamp
	0, // 7: anytty.cloud.v1.EdgePublicCertificateApplied.status:type_name -> anytty.cloud.v1.EdgePublicCertificateStatus
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_cloud_v1_certificate_proto_init() }
func file_cloud_v1_certificate_proto_init() {
	if File_cloud_v1_certificate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_v1_certificate_proto_rawDesc), len(file_cloud_v1_certificate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_v1_certificate_proto_goTypes,
		DependencyIndexes: file_cloud_v1_certificate_proto_depIdxs,
		MessageInfos:      file_cloud_v1_certificate_proto_msgTypes,
	}.Build()
	File_cloud_v1_certificate_proto = out.File
	file_cloud_v1_certificate_proto_goTypes = nil
	file_cloud_v1_certificate_proto_depIdxs = nil
}
