// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cloud/v1/client_gateway.proto

package cloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelectedCloudPath int32

const (
	SelectedCloudPath_SELECTED_CLOUD_PATH_UNSPECIFIED SelectedCloudPath = 0
	SelectedCloudPath_SELECTED_CLOUD_PATH_DIRECT      SelectedCloudPath = 1
	SelectedCloudPath_SELECTED_CLOUD_PATH_RELAY       SelectedCloudPath = 2
)

// Enum value maps for SelectedCloudPath.
var (
	SelectedCloudPath_name = map[int32]string{
		0: "SELECTED_CLOUD_PATH_UNSPECIFIED",
		1: "SELECTED_CLOUD_PATH_DIRECT",
		2: "SELECTED_CLOUD_PATH_RELAY",
	}
	SelectedCloudPath_value = map[string]int32{
		"SELECTED_CLOUD_PATH_UNSPECIFIED": 0,
		"SELECTED_CLOUD_PATH_DIRECT":      1,
		"SELECTED_CLOUD_PATH_RELAY":       2,
	}
)

func (x SelectedCloudPath) Enum() *SelectedCloudPath {
	p := new(SelectedCloudPath)
	*p = x
	return p
}

func (x SelectedCloudPath) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SelectedCloudPath) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_client_gateway_proto_enumTypes[0].Descriptor()
}

func (SelectedCloudPath) Type() protoreflect.EnumType {
	return &file_cloud_v1_client_gateway_proto_enumTypes[0]
}

func (x SelectedCloudPath) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SelectedCloudPath.Descriptor instead.
func (SelectedCloudPath) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{0}
}

type CloudPathDecision int32

const (
	CloudPathDecision_CLOUD_PATH_DECISION_UNSPECIFIED    CloudPathDecision = 0
	CloudPathDecision_CLOUD_PATH_DECISION_CONFIRM_DIRECT CloudPathDecision = 1
	CloudPathDecision_CLOUD_PATH_DECISION_CONFIRM_RELAY  CloudPathDecision = 2
	CloudPathDecision_CLOUD_PATH_DECISION_ABANDON        CloudPathDecision = 3
)

// Enum value maps for CloudPathDecision.
var (
	CloudPathDecision_name = map[int32]string{
		0: "CLOUD_PATH_DECISION_UNSPECIFIED",
		1: "CLOUD_PATH_DECISION_CONFIRM_DIRECT",
		2: "CLOUD_PATH_DECISION_CONFIRM_RELAY",
		3: "CLOUD_PATH_DECISION_ABANDON",
	}
	CloudPathDecision_value = map[string]int32{
		"CLOUD_PATH_DECISION_UNSPECIFIED":    0,
		"CLOUD_PATH_DECISION_CONFIRM_DIRECT": 1,
		"CLOUD_PATH_DECISION_CONFIRM_RELAY":  2,
		"CLOUD_PATH_DECISION_ABANDON":        3,
	}
)

func (x CloudPathDecision) Enum() *CloudPathDecision {
	p := new(CloudPathDecision)
	*p = x
	return p
}

func (x CloudPathDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CloudPathDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_client_gateway_proto_enumTypes[1].Descriptor()
}

func (CloudPathDecision) Type() protoreflect.EnumType {
	return &file_cloud_v1_client_gateway_proto_enumTypes[1]
}

func (x CloudPathDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CloudPathDecision.Descriptor instead.
func (CloudPathDecision) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{1}
}

type SignalSessionCloseCode int32

const (
	SignalSessionCloseCode_SIGNAL_SESSION_CLOSE_CODE_UNSPECIFIED      SignalSessionCloseCode = 0
	SignalSessionCloseCode_SIGNAL_SESSION_CLOSE_CODE_ADMIN_DISCONNECT SignalSessionCloseCode = 1
)

// Enum value maps for SignalSessionCloseCode.
var (
	SignalSessionCloseCode_name = map[int32]string{
		0: "SIGNAL_SESSION_CLOSE_CODE_UNSPECIFIED",
		1: "SIGNAL_SESSION_CLOSE_CODE_ADMIN_DISCONNECT",
	}
	SignalSessionCloseCode_value = map[string]int32{
		"SIGNAL_SESSION_CLOSE_CODE_UNSPECIFIED":      0,
		"SIGNAL_SESSION_CLOSE_CODE_ADMIN_DISCONNECT": 1,
	}
)

func (x SignalSessionCloseCode) Enum() *SignalSessionCloseCode {
	p := new(SignalSessionCloseCode)
	*p = x
	return p
}

func (x SignalSessionCloseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SignalSessionCloseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_client_gateway_proto_enumTypes[2].Descriptor()
}

func (SignalSessionCloseCode) Type() protoreflect.EnumType {
	return &file_cloud_v1_client_gateway_proto_enumTypes[2]
}

func (x SignalSessionCloseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SignalSessionCloseCode.Descriptor instead.
func (SignalSessionCloseCode) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{2}
}

// CloudICECandidate 是 Cloud 信令的中性 candidate；不携带授权或 terminal 数据。
type CloudICECandidate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Candidate        string                 `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	SdpMid           string                 `protobuf:"bytes,2,opt,name=sdp_mid,json=sdpMid,proto3" json:"sdp_mid,omitempty"`
	SdpMlineIndex    uint32                 `protobuf:"varint,3,opt,name=sdp_mline_index,json=sdpMlineIndex,proto3" json:"sdp_mline_index,omitempty"`
	UsernameFragment string                 `protobuf:"bytes,4,opt,name=username_fragment,json=usernameFragment,proto3" json:"username_fragment,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CloudICECandidate) Reset() {
	*x = CloudICECandidate{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloudICECandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloudICECandidate) ProtoMessage() {}

func (x *CloudICECandidate) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloudICECandidate.ProtoReflect.Descriptor instead.
func (*CloudICECandidate) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *CloudICECandidate) GetCandidate() string {
	if x != nil {
		return x.Candidate
	}
	return ""
}

func (x *CloudICECandidate) GetSdpMid() string {
	if x != nil {
		return x.SdpMid
	}
	return ""
}

func (x *CloudICECandidate) GetSdpMlineIndex() uint32 {
	if x != nil {
		return x.SdpMlineIndex
	}
	return 0
}

func (x *CloudICECandidate) GetUsernameFragment() string {
	if x != nil {
		return x.UsernameFragment
	}
	return ""
}

// PairingAdmission 是二维码材料的网络投影。Edge 必须将其与当前在线 daemon binding 对齐，
// 再向该 daemon 实时请求授权；它自身不是 grant，也不能兑换 capability。
type PairingAdmission struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DaemonId           string                 `protobuf:"bytes,1,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	DeviceId           string                 `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	DevicePublicKey    []byte                 `protobuf:"bytes,3,opt,name=device_public_key,json=devicePublicKey,proto3" json:"device_public_key,omitempty"`
	PairingClaimSha256 []byte                 `protobuf:"bytes,4,opt,name=pairing_claim_sha256,json=pairingClaimSha256,proto3" json:"pairing_claim_sha256,omitempty"`
	ExpiresAtUnixNano  int64                  `protobuf:"varint,5,opt,name=expires_at_unix_nano,json=expiresAtUnixNano,proto3" json:"expires_at_unix_nano,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PairingAdmission) Reset() {
	*x = PairingAdmission{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairingAdmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairingAdmission) ProtoMessage() {}

func (x *PairingAdmission) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairingAdmission.ProtoReflect.Descriptor instead.
func (*PairingAdmission) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *PairingAdmission) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *PairingAdmission) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PairingAdmission) GetDevicePublicKey() []byte {
	if x != nil {
		return x.DevicePublicKey
	}
	return nil
}

func (x *PairingAdmission) GetPairingClaimSha256() []byte {
	if x != nil {
		return x.PairingClaimSha256
	}
	return nil
}

func (x *PairingAdmission) GetExpiresAtUnixNano() int64 {
	if x != nil {
		return x.ExpiresAtUnixNano
	}
	return 0
}

type ClientHello struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClientPublicKey   []byte                 `protobuf:"bytes,2,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	ClientProof       []byte                 `protobuf:"bytes,3,opt,name=client_proof,json=clientProof,proto3" json:"client_proof,omitempty"`
	Product           ClientProduct          `protobuf:"varint,4,opt,name=product,proto3,enum=anytty.cloud.v1.ClientProduct" json:"product,omitempty"`
	SoftwareVersion   string                 `protobuf:"bytes,5,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	AttemptGeneration uint64                 `protobuf:"varint,6,opt,name=attempt_generation,json=attemptGeneration,proto3" json:"attempt_generation,omitempty"`
	RelayPreference   RelayPreference        `protobuf:"varint,7,opt,name=relay_preference,json=relayPreference,proto3,enum=anytty.cloud.v1.RelayPreference" json:"relay_preference,omitempty"`
	// presence_probe only verifies this daemon's live AgentGateway presence.
	// It never allocates a ClientSession, Relay reservation, or WebRTC peer.
	PresenceProbe bool `protobuf:"varint,8,opt,name=presence_probe,json=presenceProbe,proto3" json:"presence_probe,omitempty"`
	// Types that are valid to be assigned to Authorization:
	//
	//	*ClientHello_CloudRouteGrant
	//	*ClientHello_PairingAdmission
	Authorization isClientHello_Authorization `protobuf_oneof:"authorization"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *ClientHello) GetClientPublicKey() []byte {
	if x != nil {
		return x.ClientPublicKey
	}
	return nil
}

func (x *ClientHello) GetClientProof() []byte {
	if x != nil {
		return x.ClientProof
	}
	return nil
}

func (x *ClientHello) GetProduct() ClientProduct {
	if x != nil {
		return x.Product
	}
	return ClientProduct_CLIENT_PRODUCT_UNSPECIFIED
}

func (x *ClientHello) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *ClientHello) GetAttemptGeneration() uint64 {
	if x != nil {
		return x.AttemptGeneration
	}
	return 0
}

func (x *ClientHello) GetRelayPreference() RelayPreference {
	if x != nil {
		return x.RelayPreference
	}
	return RelayPreference_RELAY_PREFERENCE_UNSPECIFIED
}

func (x *ClientHello) GetPresenceProbe() bool {
	if x != nil {
		return x.PresenceProbe
	}
	return false
}

func (x *ClientHello) GetAuthorization() isClientHello_Authorization {
	if x != nil {
		return x.Authorization
	}
	return nil
}

func (x *ClientHello) GetCloudRouteGrant() *SignedEnvelope {
	if x != nil {
		if x, ok := x.Authorization.(*ClientHello_CloudRouteGrant); ok {
			return x.CloudRouteGrant
		}
	}
	return nil
}

func (x *ClientHello) GetPairingAdmission() *PairingAdmission {
	if x != nil {
		if x, ok := x.Authorization.(*ClientHello_PairingAdmission); ok {
			return x.PairingAdmission
		}
	}
	return nil
}

type isClientHello_Authorization interface {
	isClientHello_Authorization()
}

type ClientHello_CloudRouteGrant struct {
	// cloud_route_grant 是 owning daemon 签发给已配对 ClientAccessIdentity 的长期发现和信令授权。
	CloudRouteGrant *SignedEnvelope `protobuf:"bytes,10,opt,name=cloud_route_grant,json=cloudRouteGrant,proto3,oneof"`
}

type ClientHello_PairingAdmission struct {
	// pairing_admission 只允许 Edge 向在线 daemon 请求一次性 pairing 预检。
	PairingAdmission *PairingAdmission `protobuf:"bytes,11,opt,name=pairing_admission,json=pairingAdmission,proto3,oneof"`
}

func (*ClientHello_CloudRouteGrant) isClientHello_Authorization() {}

func (*ClientHello_PairingAdmission) isClientHello_Authorization() {}

type ClientReady struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SessionId  string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Generation uint64                 `protobuf:"varint,2,opt,name=generation,proto3" json:"generation,omitempty"`
	Relay      *RelayICEConfig        `protobuf:"bytes,3,opt,name=relay,proto3" json:"relay,omitempty"`
	// AUTO 可以继续纯 P2P；只有 P2P 最终也失败时客户端才展示该原因。
	RelayFailure  *CloudEntitlementFailure `protobuf:"bytes,4,opt,name=relay_failure,json=relayFailure,proto3" json:"relay_failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientReady) Reset() {
	*x = ClientReady{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientReady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientReady) ProtoMessage() {}

func (x *ClientReady) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientReady.ProtoReflect.Descriptor instead.
func (*ClientReady) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *ClientReady) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientReady) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ClientReady) GetRelay() *RelayICEConfig {
	if x != nil {
		return x.Relay
	}
	return nil
}

func (x *ClientReady) GetRelayFailure() *CloudEntitlementFailure {
	if x != nil {
		return x.RelayFailure
	}
	return nil
}

// ClientPathDecision commits or abandons one authenticated candidate. The
// decision_id is stable across same-stream retries and cannot be reused for a
// different decision.
type ClientPathDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DecisionId    string                 `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Decision      CloudPathDecision      `protobuf:"varint,3,opt,name=decision,proto3,enum=anytty.cloud.v1.CloudPathDecision" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPathDecision) Reset() {
	*x = ClientPathDecision{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPathDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPathDecision) ProtoMessage() {}

func (x *ClientPathDecision) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPathDecision.ProtoReflect.Descriptor instead.
func (*ClientPathDecision) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *ClientPathDecision) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientPathDecision) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *ClientPathDecision) GetDecision() CloudPathDecision {
	if x != nil {
		return x.Decision
	}
	return CloudPathDecision_CLOUD_PATH_DECISION_UNSPECIFIED
}

// EdgePathDecisionAck is the only release barrier accepted by the client. For
// DIRECT and ABANDON, Edge sends it only after the provisional Relay
// reservation reached its durable terminal state; ABANDON also requires the
// runtime session projection to be removed.
type EdgePathDecisionAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	DecisionId    string                 `protobuf:"bytes,2,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Decision      CloudPathDecision      `protobuf:"varint,3,opt,name=decision,proto3,enum=anytty.cloud.v1.CloudPathDecision" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgePathDecisionAck) Reset() {
	*x = EdgePathDecisionAck{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgePathDecisionAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgePathDecisionAck) ProtoMessage() {}

func (x *EdgePathDecisionAck) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgePathDecisionAck.ProtoReflect.Descriptor instead.
func (*EdgePathDecisionAck) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *EdgePathDecisionAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EdgePathDecisionAck) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *EdgePathDecisionAck) GetDecision() CloudPathDecision {
	if x != nil {
		return x.Decision
	}
	return CloudPathDecision_CLOUD_PATH_DECISION_UNSPECIFIED
}

// ClientSessionRelease is a separate teardown transaction for a path that was
// already confirmed. It must not reuse or mutate the immutable PathDecision.
type ClientSessionRelease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ReleaseId     string                 `protobuf:"bytes,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSessionRelease) Reset() {
	*x = ClientSessionRelease{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSessionRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSessionRelease) ProtoMessage() {}

func (x *ClientSessionRelease) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSessionRelease.ProtoReflect.Descriptor instead.
func (*ClientSessionRelease) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *ClientSessionRelease) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientSessionRelease) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

// EdgeSessionReleaseAck is emitted only after Relay and runtime session
// cleanup completed. EOF and administrative close are not release ACKs.
type EdgeSessionReleaseAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ReleaseId     string                 `protobuf:"bytes,2,opt,name=release_id,json=releaseId,proto3" json:"release_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeSessionReleaseAck) Reset() {
	*x = EdgeSessionReleaseAck{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeSessionReleaseAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeSessionReleaseAck) ProtoMessage() {}

func (x *EdgeSessionReleaseAck) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeSessionReleaseAck.ProtoReflect.Descriptor instead.
func (*EdgeSessionReleaseAck) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *EdgeSessionReleaseAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EdgeSessionReleaseAck) GetReleaseId() string {
	if x != nil {
		return x.ReleaseId
	}
	return ""
}

type ClientOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OfferSdp      string                 `protobuf:"bytes,2,opt,name=offer_sdp,json=offerSdp,proto3" json:"offer_sdp,omitempty"`
	Candidates    []*CloudICECandidate   `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientOffer) Reset() {
	*x = ClientOffer{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientOffer) ProtoMessage() {}

func (x *ClientOffer) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientOffer.ProtoReflect.Descriptor instead.
func (*ClientOffer) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *ClientOffer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ClientOffer) GetOfferSdp() string {
	if x != nil {
		return x.OfferSdp
	}
	return ""
}

func (x *ClientOffer) GetCandidates() []*CloudICECandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type EdgeAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AnswerSdp     string                 `protobuf:"bytes,2,opt,name=answer_sdp,json=answerSdp,proto3" json:"answer_sdp,omitempty"`
	Candidates    []*CloudICECandidate   `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeAnswer) Reset() {
	*x = EdgeAnswer{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeAnswer) ProtoMessage() {}

func (x *EdgeAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeAnswer.ProtoReflect.Descriptor instead.
func (*EdgeAnswer) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *EdgeAnswer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EdgeAnswer) GetAnswerSdp() string {
	if x != nil {
		return x.AnswerSdp
	}
	return ""
}

func (x *EdgeAnswer) GetCandidates() []*CloudICECandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type SignalRejected struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	SessionId          string                   `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Code               string                   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message            string                   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EntitlementFailure *CloudEntitlementFailure `protobuf:"bytes,4,opt,name=entitlement_failure,json=entitlementFailure,proto3" json:"entitlement_failure,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SignalRejected) Reset() {
	*x = SignalRejected{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalRejected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalRejected) ProtoMessage() {}

func (x *SignalRejected) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalRejected.ProtoReflect.Descriptor instead.
func (*SignalRejected) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *SignalRejected) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SignalRejected) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *SignalRejected) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SignalRejected) GetEntitlementFailure() *CloudEntitlementFailure {
	if x != nil {
		return x.EntitlementFailure
	}
	return nil
}

type SignalSessionClosed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Code          SignalSessionCloseCode `protobuf:"varint,2,opt,name=code,proto3,enum=anytty.cloud.v1.SignalSessionCloseCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalSessionClosed) Reset() {
	*x = SignalSessionClosed{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalSessionClosed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalSessionClosed) ProtoMessage() {}

func (x *SignalSessionClosed) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalSessionClosed.ProtoReflect.Descriptor instead.
func (*SignalSessionClosed) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *SignalSessionClosed) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SignalSessionClosed) GetCode() SignalSessionCloseCode {
	if x != nil {
		return x.Code
	}
	return SignalSessionCloseCode_SIGNAL_SESSION_CLOSE_CODE_UNSPECIFIED
}

func (x *SignalSessionClosed) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// DaemonPresence is returned only after an authenticated presence probe.
// online=false intentionally covers offline, stale, and invalid authorization
// so the endpoint cannot be enumerated without a valid CloudRouteGrant.
type DaemonPresence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Online        bool                   `protobuf:"varint,1,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DaemonPresence) Reset() {
	*x = DaemonPresence{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DaemonPresence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DaemonPresence) ProtoMessage() {}

func (x *DaemonPresence) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DaemonPresence.ProtoReflect.Descriptor instead.
func (*DaemonPresence) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *DaemonPresence) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

type ClientSignal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MessageId       string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	BootId          string                 `protobuf:"bytes,4,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	ConnectionId    string                 `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	StreamSeq       uint64                 `protobuf:"varint,6,opt,name=stream_seq,json=streamSeq,proto3" json:"stream_seq,omitempty"`
	SentAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientSignal_Hello
	//	*ClientSignal_Offer
	//	*ClientSignal_PathDecision
	//	*ClientSignal_SessionRelease
	Payload       isClientSignal_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSignal) Reset() {
	*x = ClientSignal{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSignal) ProtoMessage() {}

func (x *ClientSignal) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSignal.ProtoReflect.Descriptor instead.
func (*ClientSignal) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *ClientSignal) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ClientSignal) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ClientSignal) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ClientSignal) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *ClientSignal) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ClientSignal) GetStreamSeq() uint64 {
	if x != nil {
		return x.StreamSeq
	}
	return 0
}

func (x *ClientSignal) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *ClientSignal) GetPayload() isClientSignal_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientSignal) GetHello() *ClientHello {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientSignal) GetOffer() *ClientOffer {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_Offer); ok {
			return x.Offer
		}
	}
	return nil
}

func (x *ClientSignal) GetPathDecision() *ClientPathDecision {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_PathDecision); ok {
			return x.PathDecision
		}
	}
	return nil
}

func (x *ClientSignal) GetSessionRelease() *ClientSessionRelease {
	if x != nil {
		if x, ok := x.Payload.(*ClientSignal_SessionRelease); ok {
			return x.SessionRelease
		}
	}
	return nil
}

type isClientSignal_Payload interface {
	isClientSignal_Payload()
}

type ClientSignal_Hello struct {
	Hello *ClientHello `protobuf:"bytes,20,opt,name=hello,proto3,oneof"`
}

type ClientSignal_Offer struct {
	Offer *ClientOffer `protobuf:"bytes,21,opt,name=offer,proto3,oneof"`
}

type ClientSignal_PathDecision struct {
	PathDecision *ClientPathDecision `protobuf:"bytes,22,opt,name=path_decision,json=pathDecision,proto3,oneof"`
}

type ClientSignal_SessionRelease struct {
	SessionRelease *ClientSessionRelease `protobuf:"bytes,23,opt,name=session_release,json=sessionRelease,proto3,oneof"`
}

func (*ClientSignal_Hello) isClientSignal_Payload() {}

func (*ClientSignal_Offer) isClientSignal_Payload() {}

func (*ClientSignal_PathDecision) isClientSignal_Payload() {}

func (*ClientSignal_SessionRelease) isClientSignal_Payload() {}

type EdgeSignal struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MessageId       string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SenderId        string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	BootId          string                 `protobuf:"bytes,4,opt,name=boot_id,json=bootId,proto3" json:"boot_id,omitempty"`
	ConnectionId    string                 `protobuf:"bytes,5,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	StreamSeq       uint64                 `protobuf:"varint,6,opt,name=stream_seq,json=streamSeq,proto3" json:"stream_seq,omitempty"`
	SentAt          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*EdgeSignal_Ready
	//	*EdgeSignal_Answer
	//	*EdgeSignal_Rejected
	//	*EdgeSignal_Challenge
	//	*EdgeSignal_Closed
	//	*EdgeSignal_Presence
	//	*EdgeSignal_PathDecisionAck
	//	*EdgeSignal_SessionReleaseAck
	Payload       isEdgeSignal_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeSignal) Reset() {
	*x = EdgeSignal{}
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeSignal) ProtoMessage() {}

func (x *EdgeSignal) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_client_gateway_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeSignal.ProtoReflect.Descriptor instead.
func (*EdgeSignal) Descriptor() ([]byte, []int) {
	return file_cloud_v1_client_gateway_proto_rawDescGZIP(), []int{14}
}

func (x *EdgeSignal) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *EdgeSignal) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EdgeSignal) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *EdgeSignal) GetBootId() string {
	if x != nil {
		return x.BootId
	}
	return ""
}

func (x *EdgeSignal) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *EdgeSignal) GetStreamSeq() uint64 {
	if x != nil {
		return x.StreamSeq
	}
	return 0
}

func (x *EdgeSignal) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *EdgeSignal) GetPayload() isEdgeSignal_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EdgeSignal) GetReady() *ClientReady {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_Ready); ok {
			return x.Ready
		}
	}
	return nil
}

func (x *EdgeSignal) GetAnswer() *EdgeAnswer {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_Answer); ok {
			return x.Answer
		}
	}
	return nil
}

func (x *EdgeSignal) GetRejected() *SignalRejected {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_Rejected); ok {
			return x.Rejected
		}
	}
	return nil
}

func (x *EdgeSignal) GetChallenge() *EdgeChallenge {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_Challenge); ok {
			return x.Challenge
		}
	}
	return nil
}

func (x *EdgeSignal) GetClosed() *SignalSessionClosed {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_Closed); ok {
			return x.Closed
		}
	}
	return nil
}

func (x *EdgeSignal) GetPresence() *DaemonPresence {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_Presence); ok {
			return x.Presence
		}
	}
	return nil
}

func (x *EdgeSignal) GetPathDecisionAck() *EdgePathDecisionAck {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_PathDecisionAck); ok {
			return x.PathDecisionAck
		}
	}
	return nil
}

func (x *EdgeSignal) GetSessionReleaseAck() *EdgeSessionReleaseAck {
	if x != nil {
		if x, ok := x.Payload.(*EdgeSignal_SessionReleaseAck); ok {
			return x.SessionReleaseAck
		}
	}
	return nil
}

type isEdgeSignal_Payload interface {
	isEdgeSignal_Payload()
}

type EdgeSignal_Ready struct {
	Ready *ClientReady `protobuf:"bytes,20,opt,name=ready,proto3,oneof"`
}

type EdgeSignal_Answer struct {
	Answer *EdgeAnswer `protobuf:"bytes,21,opt,name=answer,proto3,oneof"`
}

type EdgeSignal_Rejected struct {
	Rejected *SignalRejected `protobuf:"bytes,22,opt,name=rejected,proto3,oneof"`
}

type EdgeSignal_Challenge struct {
	Challenge *EdgeChallenge `protobuf:"bytes,23,opt,name=challenge,proto3,oneof"`
}

type EdgeSignal_Closed struct {
	Closed *SignalSessionClosed `protobuf:"bytes,24,opt,name=closed,proto3,oneof"`
}

type EdgeSignal_Presence struct {
	Presence *DaemonPresence `protobuf:"bytes,25,opt,name=presence,proto3,oneof"`
}

type EdgeSignal_PathDecisionAck struct {
	PathDecisionAck *EdgePathDecisionAck `protobuf:"bytes,26,opt,name=path_decision_ack,json=pathDecisionAck,proto3,oneof"`
}

type EdgeSignal_SessionReleaseAck struct {
	SessionReleaseAck *EdgeSessionReleaseAck `protobuf:"bytes,27,opt,name=session_release_ack,json=sessionReleaseAck,proto3,oneof"`
}

func (*EdgeSignal_Ready) isEdgeSignal_Payload() {}

func (*EdgeSignal_Answer) isEdgeSignal_Payload() {}

func (*EdgeSignal_Rejected) isEdgeSignal_Payload() {}

func (*EdgeSignal_Challenge) isEdgeSignal_Payload() {}

func (*EdgeSignal_Closed) isEdgeSignal_Payload() {}

func (*EdgeSignal_Presence) isEdgeSignal_Payload() {}

func (*EdgeSignal_PathDecisionAck) isEdgeSignal_Payload() {}

func (*EdgeSignal_SessionReleaseAck) isEdgeSignal_Payload() {}

var File_cloud_v1_client_gateway_proto protoreflect.FileDescriptor

const file_cloud_v1_client_gateway_proto_rawDesc = "" +
	"\n" +
	"\x1dcloud/v1/client_gateway.proto\x12\x0fanytty.cloud.v1\x1a\x15cloud/v1/common.proto\x1a\x16cloud/v1/runtime.proto\x1a\x14cloud/v1/usage.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9f\x01\n" +
	"\x11CloudICECandidate\x12\x1c\n" +
	"\tcandidate\x18\x01 \x01(\tR\tcandidate\x12\x17\n" +
	"\asdp_mid\x18\x02 \x01(\tR\x06sdpMid\x12&\n" +
	"\x0fsdp_mline_index\x18\x03 \x01(\rR\rsdpMlineIndex\x12+\n" +
	"\x11username_fragment\x18\x04 \x01(\tR\x10usernameFragment\"\xdb\x01\n" +
	"\x10PairingAdmission\x12\x1b\n" +
	"\tdaemon_id\x18\x01 \x01(\tR\bdaemonId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12*\n" +
	"\x11device_public_key\x18\x03 \x01(\fR\x0fdevicePublicKey\x120\n" +
	"\x14pairing_claim_sha256\x18\x04 \x01(\fR\x12pairingClaimSha256\x12/\n" +
	"\x14expires_at_unix_nano\x18\x05 \x01(\x03R\x11expiresAtUnixNano\"\x96\x04\n" +
	"\vClientHello\x12*\n" +
	"\x11client_public_key\x18\x02 \x01(\fR\x0fclientPublicKey\x12!\n" +
	"\fclient_proof\x18\x03 \x01(\fR\vclientProof\x128\n" +
	"\aproduct\x18\x04 \x01(\x0e2\x1e.anytty.cloud.v1.ClientProductR\aproduct\x12)\n" +
	"\x10software_version\x18\x05 \x01(\tR\x0fsoftwareVersion\x12-\n" +
	"\x12attempt_generation\x18\x06 \x01(\x04R\x11attemptGeneration\x12K\n" +
	"\x10relay_preference\x18\a \x01(\x0e2 .anytty.cloud.v1.RelayPreferenceR\x0frelayPreference\x12%\n" +
	"\x0epresence_probe\x18\b \x01(\bR\rpresenceProbe\x12M\n" +
	"\x11cloud_route_grant\x18\n" +
	" \x01(\v2\x1f.anytty.cloud.v1.SignedEnvelopeH\x00R\x0fcloudRouteGrant\x12P\n" +
	"\x11pairing_admission\x18\v \x01(\v2!.anytty.cloud.v1.PairingAdmissionH\x00R\x10pairingAdmissionB\x0f\n" +
	"\rauthorization\"\xd2\x01\n" +
	"\vClientReady\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1e\n" +
	"\n" +
	"generation\x18\x02 \x01(\x04R\n" +
	"generation\x125\n" +
	"\x05relay\x18\x03 \x01(\v2\x1f.anytty.cloud.v1.RelayICEConfigR\x05relay\x12M\n" +
	"\rrelay_failure\x18\x04 \x01(\v2(.anytty.cloud.v1.CloudEntitlementFailureR\frelayFailure\"\x94\x01\n" +
	"\x12ClientPathDecision\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x12>\n" +
	"\bdecision\x18\x03 \x01(\x0e2\".anytty.cloud.v1.CloudPathDecisionR\bdecision\"\x95\x01\n" +
	"\x13EdgePathDecisionAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vdecision_id\x18\x02 \x01(\tR\n" +
	"decisionId\x12>\n" +
	"\bdecision\x18\x03 \x01(\x0e2\".anytty.cloud.v1.CloudPathDecisionR\bdecision\"T\n" +
	"\x14ClientSessionRelease\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"release_id\x18\x02 \x01(\tR\treleaseId\"U\n" +
	"\x15EdgeSessionReleaseAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"release_id\x18\x02 \x01(\tR\treleaseId\"\x8d\x01\n" +
	"\vClientOffer\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\toffer_sdp\x18\x02 \x01(\tR\bofferSdp\x12B\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\".anytty.cloud.v1.CloudICECandidateR\n" +
	"candidates\"\x8e\x01\n" +
	"\n" +
	"EdgeAnswer\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"answer_sdp\x18\x02 \x01(\tR\tanswerSdp\x12B\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\".anytty.cloud.v1.CloudICECandidateR\n" +
	"candidates\"\xb8\x01\n" +
	"\x0eSignalRejected\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12Y\n" +
	"\x13entitlement_failure\x18\x04 \x01(\v2(.anytty.cloud.v1.CloudEntitlementFailureR\x12entitlementFailure\"\x8b\x01\n" +
	"\x13SignalSessionClosed\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12;\n" +
	"\x04code\x18\x02 \x01(\x0e2'.anytty.cloud.v1.SignalSessionCloseCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"(\n" +
	"\x0eDaemonPresence\x12\x16\n" +
	"\x06online\x18\x01 \x01(\bR\x06online\"\x9c\x04\n" +
	"\fClientSignal\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x17\n" +
	"\aboot_id\x18\x04 \x01(\tR\x06bootId\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\x12\x1d\n" +
	"\n" +
	"stream_seq\x18\x06 \x01(\x04R\tstreamSeq\x123\n" +
	"\asent_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x124\n" +
	"\x05hello\x18\x14 \x01(\v2\x1c.anytty.cloud.v1.ClientHelloH\x00R\x05hello\x124\n" +
	"\x05offer\x18\x15 \x01(\v2\x1c.anytty.cloud.v1.ClientOfferH\x00R\x05offer\x12J\n" +
	"\rpath_decision\x18\x16 \x01(\v2#.anytty.cloud.v1.ClientPathDecisionH\x00R\fpathDecision\x12P\n" +
	"\x0fsession_release\x18\x17 \x01(\v2%.anytty.cloud.v1.ClientSessionReleaseH\x00R\x0esessionReleaseB\t\n" +
	"\apayload\"\xa9\x06\n" +
	"\n" +
	"EdgeSignal\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x17\n" +
	"\aboot_id\x18\x04 \x01(\tR\x06bootId\x12#\n" +
	"\rconnection_id\x18\x05 \x01(\tR\fconnectionId\x12\x1d\n" +
	"\n" +
	"stream_seq\x18\x06 \x01(\x04R\tstreamSeq\x123\n" +
	"\asent_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x124\n" +
	"\x05ready\x18\x14 \x01(\v2\x1c.anytty.cloud.v1.ClientReadyH\x00R\x05ready\x125\n" +
	"\x06answer\x18\x15 \x01(\v2\x1b.anytty.cloud.v1.EdgeAnswerH\x00R\x06answer\x12=\n" +
	"\brejected\x18\x16 \x01(\v2\x1f.anytty.cloud.v1.SignalRejectedH\x00R\brejected\x12>\n" +
	"\tchallenge\x18\x17 \x01(\v2\x1e.anytty.cloud.v1.EdgeChallengeH\x00R\tchallenge\x12>\n" +
	"\x06closed\x18\x18 \x01(\v2$.anytty.cloud.v1.SignalSessionClosedH\x00R\x06closed\x12=\n" +
	"\bpresence\x18\x19 \x01(\v2\x1f.anytty.cloud.v1.DaemonPresenceH\x00R\bpresence\x12R\n" +
	"\x11path_decision_ack\x18\x1a \x01(\v2$.anytty.cloud.v1.EdgePathDecisionAckH\x00R\x0fpathDecisionAck\x12X\n" +
	"\x13session_release_ack\x18\x1b \x01(\v2&.anytty.cloud.v1.EdgeSessionReleaseAckH\x00R\x11sessionReleaseAckB\t\n" +
	"\apayload*w\n" +
	"\x11SelectedCloudPath\x12#\n" +
	"\x1fSELECTED_CLOUD_PATH_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSELECTED_CLOUD_PATH_DIRECT\x10\x01\x12\x1d\n" +
	"\x19SELECTED_CLOUD_PATH_RELAY\x10\x02*\xa8\x01\n" +
	"\x11CloudPathDecision\x12#\n" +
	"\x1fCLOUD_PATH_DECISION_UNSPECIFIED\x10\x00\x12&\n" +
	"\"CLOUD_PATH_DECISION_CONFIRM_DIRECT\x10\x01\x12%\n" +
	"!CLOUD_PATH_DECISION_CONFIRM_RELAY\x10\x02\x12\x1f\n" +
	"\x1bCLOUD_PATH_DECISION_ABANDON\x10\x03*s\n" +
	"\x16SignalSessionCloseCode\x12)\n" +
	"%SIGNAL_SESSION_CLOSE_CODE_UNSPECIFIED\x10\x00\x12.\n" +
	"*SIGNAL_SESSION_CLOSE_CODE_ADMIN_DISCONNECT\x10\x012Z\n" +
	"\rClientGateway\x12I\n" +
	"\aConnect\x12\x1d.anytty.cloud.v1.ClientSignal\x1a\x1b.anytty.cloud.v1.EdgeSignal(\x010\x01B1Z/github.com/anytty/anytty/proto/cloud/v1;cloudv1b\x06proto3"

var (
	file_cloud_v1_client_gateway_proto_rawDescOnce sync.Once
	file_cloud_v1_client_gateway_proto_rawDescData []byte
)

func file_cloud_v1_client_gateway_proto_rawDescGZIP() []byte {
	file_cloud_v1_client_gateway_proto_rawDescOnce.Do(func() {
		file_cloud_v1_client_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_v1_client_gateway_proto_rawDesc), len(file_cloud_v1_client_gateway_proto_rawDesc)))
	})
	return file_cloud_v1_client_gateway_proto_rawDescData
}

var file_cloud_v1_client_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_cloud_v1_client_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_cloud_v1_client_gateway_proto_goTypes = []any{
	(SelectedCloudPath)(0),          // 0: anytty.cloud.v1.SelectedCloudPath
	(CloudPathDecision)(0),          // 1: anytty.cloud.v1.CloudPathDecision
	(SignalSessionCloseCode)(0),     // 2: anytty.cloud.v1.SignalSessionCloseCode
	(*CloudICECandidate)(nil),       // 3: anytty.cloud.v1.CloudICECandidate
	(*PairingAdmission)(nil),        // 4: anytty.cloud.v1.PairingAdmission
	(*ClientHello)(nil),             // 5: anytty.cloud.v1.ClientHello
	(*ClientReady)(nil),             // 6: anytty.cloud.v1.ClientReady
	(*ClientPathDecision)(nil),      // 7: anytty.cloud.v1.ClientPathDecision
	(*EdgePathDecisionAck)(nil),     // 8: anytty.cloud.v1.EdgePathDecisionAck
	(*ClientSessionRelease)(nil),    // 9: anytty.cloud.v1.ClientSessionRelease
	(*EdgeSessionReleaseAck)(nil),   // 10: anytty.cloud.v1.EdgeSessionReleaseAck
	(*ClientOffer)(nil),             // 11: anytty.cloud.v1.ClientOffer
	(*EdgeAnswer)(nil),              // 12: anytty.cloud.v1.EdgeAnswer
	(*SignalRejected)(nil),          // 13: anytty.cloud.v1.SignalRejected
	(*SignalSessionClosed)(nil),     // 14: anytty.cloud.v1.SignalSessionClosed
	(*DaemonPresence)(nil),          // 15: anytty.cloud.v1.DaemonPresence
	(*ClientSignal)(nil),            // 16: anytty.cloud.v1.ClientSignal
	(*EdgeSignal)(nil),              // 17: anytty.cloud.v1.EdgeSignal
	(ClientProduct)(0),              // 18: anytty.cloud.v1.ClientProduct
	(RelayPreference)(0),            // 19: anytty.cloud.v1.RelayPreference
	(*SignedEnvelope)(nil),          // 20: anytty.cloud.v1.SignedEnvelope
	(*RelayICEConfig)(nil),          // 21: anytty.cloud.v1.RelayICEConfig
	(*CloudEntitlementFailure)(nil), // 22: anytty.cloud.v1.CloudEntitlementFailure
	(*timestamppb.Timestamp)(nil),   // 23: google.protobuf.Timestamp
	(*EdgeChallenge)(nil),           // 24: anytty.cloud.v1.EdgeChallenge
}
var file_cloud_v1_client_gateway_proto_depIdxs = []int32{
	18, // 0: anytty.cloud.v1.ClientHello.product:type_name -> anytty.cloud.v1.ClientProduct
	19, // 1: anytty.cloud.v1.ClientHello.relay_preference:type_name -> anytty.cloud.v1.RelayPreference
	20, // 2: anytty.cloud.v1.ClientHello.cloud_route_grant:type_name -> anytty.cloud.v1.SignedEnvelope
	4,  // 3: anytty.cloud.v1.ClientHello.pairing_admission:type_name -> anytty.cloud.v1.PairingAdmission
	21, // 4: anytty.cloud.v1.ClientReady.relay:type_name -> anytty.cloud.v1.RelayICEConfig
	22, // 5: anytty.cloud.v1.ClientReady.relay_failure:type_name -> anytty.cloud.v1.CloudEntitlementFailure
	1,  // 6: anytty.cloud.v1.ClientPathDecision.decision:type_name -> anytty.cloud.v1.CloudPathDecision
	1,  // 7: anytty.cloud.v1.EdgePathDecisionAck.decision:type_name -> anytty.cloud.v1.CloudPathDecision
	3,  // 8: anytty.cloud.v1.ClientOffer.candidates:type_name -> anytty.cloud.v1.CloudICECandidate
	3,  // 9: anytty.cloud.v1.EdgeAnswer.candidates:type_name -> anytty.cloud.v1.CloudICECandidate
	22, // 10: anytty.cloud.v1.SignalRejected.entitlement_failure:type_name -> anytty.cloud.v1.CloudEntitlementFailure
	2,  // 11: anytty.cloud.v1.SignalSessionClosed.code:type_name -> anytty.cloud.v1.SignalSessionCloseCode
	23, // 12: anytty.cloud.v1.ClientSignal.sent_at:type_name -> google.protobuf.Timestamp
	5,  // 13: anytty.cloud.v1.ClientSignal.hello:type_name -> anytty.cloud.v1.ClientHello
	11, // 14: anytty.cloud.v1.ClientSignal.offer:type_name -> anytty.cloud.v1.ClientOffer
	7,  // 15: anytty.cloud.v1.ClientSignal.path_decision:type_name -> anytty.cloud.v1.ClientPathDecision
	9,  // 16: anytty.cloud.v1.ClientSignal.session_release:type_name -> anytty.cloud.v1.ClientSessionRelease
	23, // 17: anytty.cloud.v1.EdgeSignal.sent_at:type_name -> google.protobuf.Timestamp
	6,  // 18: anytty.cloud.v1.EdgeSignal.ready:type_name -> anytty.cloud.v1.ClientReady
	12, // 19: anytty.cloud.v1.EdgeSignal.answer:type_name -> anytty.cloud.v1.EdgeAnswer
	13, // 20: anytty.cloud.v1.EdgeSignal.rejected:type_name -> anytty.cloud.v1.SignalRejected
	24, // 21: anytty.cloud.v1.EdgeSignal.challenge:type_name -> anytty.cloud.v1.EdgeChallenge
	14, // 22: anytty.cloud.v1.EdgeSignal.closed:type_name -> anytty.cloud.v1.SignalSessionClosed
	15, // 23: anytty.cloud.v1.EdgeSignal.presence:type_name -> anytty.cloud.v1.DaemonPresence
	8,  // 24: anytty.cloud.v1.EdgeSignal.path_decision_ack:type_name -> anytty.cloud.v1.EdgePathDecisionAck
	10, // 25: anytty.cloud.v1.EdgeSignal.session_release_ack:type_name -> anytty.cloud.v1.EdgeSessionReleaseAck
	16, // 26: anytty.cloud.v1.ClientGateway.Connect:input_type -> anytty.cloud.v1.ClientSignal
	17, // 27: anytty.cloud.v1.ClientGateway.Connect:output_type -> anytty.cloud.v1.EdgeSignal
	27, // [27:28] is the sub-list for method output_type
	26, // [26:27] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_cloud_v1_client_gateway_proto_init() }
func file_cloud_v1_client_gateway_proto_init() {
	if File_cloud_v1_client_gateway_proto != nil {
		return
	}
	file_cloud_v1_common_proto_init()
	file_cloud_v1_runtime_proto_init()
	file_cloud_v1_usage_proto_init()
	file_cloud_v1_client_gateway_proto_msgTypes[2].OneofWrappers = []any{
		(*ClientHello_CloudRouteGrant)(nil),
		(*ClientHello_PairingAdmission)(nil),
	}
	file_cloud_v1_client_gateway_proto_msgTypes[13].OneofWrappers = []any{
		(*ClientSignal_Hello)(nil),
		(*ClientSignal_Offer)(nil),
		(*ClientSignal_PathDecision)(nil),
		(*ClientSignal_SessionRelease)(nil),
	}
	file_cloud_v1_client_gateway_proto_msgTypes[14].OneofWrappers = []any{
		(*EdgeSignal_Ready)(nil),
		(*EdgeSignal_Answer)(nil),
		(*EdgeSignal_Rejected)(nil),
		(*EdgeSignal_Challenge)(nil),
		(*EdgeSignal_Closed)(nil),
		(*EdgeSignal_Presence)(nil),
		(*EdgeSignal_PathDecisionAck)(nil),
		(*EdgeSignal_SessionReleaseAck)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_v1_client_gateway_proto_rawDesc), len(file_cloud_v1_client_gateway_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cloud_v1_client_gateway_proto_goTypes,
		DependencyIndexes: file_cloud_v1_client_gateway_proto_depIdxs,
		EnumInfos:         file_cloud_v1_client_gateway_proto_enumTypes,
		MessageInfos:      file_cloud_v1_client_gateway_proto_msgTypes,
	}.Build()
	File_cloud_v1_client_gateway_proto = out.File
	file_cloud_v1_client_gateway_proto_goTypes = nil
	file_cloud_v1_client_gateway_proto_depIdxs = nil
}
