// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: cloud/v1/usage.proto

package cloudv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RelayPreference is the ICE policy for one Cloud connection attempt.
type RelayPreference int32

const (
	RelayPreference_RELAY_PREFERENCE_UNSPECIFIED RelayPreference = 0
	RelayPreference_RELAY_PREFERENCE_AUTO        RelayPreference = 1
	RelayPreference_RELAY_PREFERENCE_DIRECT_ONLY RelayPreference = 2
	RelayPreference_RELAY_PREFERENCE_RELAY_ONLY  RelayPreference = 3
)

// Enum value maps for RelayPreference.
var (
	RelayPreference_name = map[int32]string{
		0: "RELAY_PREFERENCE_UNSPECIFIED",
		1: "RELAY_PREFERENCE_AUTO",
		2: "RELAY_PREFERENCE_DIRECT_ONLY",
		3: "RELAY_PREFERENCE_RELAY_ONLY",
	}
	RelayPreference_value = map[string]int32{
		"RELAY_PREFERENCE_UNSPECIFIED": 0,
		"RELAY_PREFERENCE_AUTO":        1,
		"RELAY_PREFERENCE_DIRECT_ONLY": 2,
		"RELAY_PREFERENCE_RELAY_ONLY":  3,
	}
)

func (x RelayPreference) Enum() *RelayPreference {
	p := new(RelayPreference)
	*p = x
	return p
}

func (x RelayPreference) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayPreference) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_usage_proto_enumTypes[0].Descriptor()
}

func (RelayPreference) Type() protoreflect.EnumType {
	return &file_cloud_v1_usage_proto_enumTypes[0]
}

func (x RelayPreference) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayPreference.Descriptor instead.
func (RelayPreference) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{0}
}

// RelayTransport is the physical TURN transport used by an Edge allocation.
type RelayTransport int32

const (
	RelayTransport_RELAY_TRANSPORT_UNSPECIFIED RelayTransport = 0
	RelayTransport_RELAY_TRANSPORT_UDP         RelayTransport = 1
	RelayTransport_RELAY_TRANSPORT_TCP         RelayTransport = 2
	RelayTransport_RELAY_TRANSPORT_TLS         RelayTransport = 3
)

// Enum value maps for RelayTransport.
var (
	RelayTransport_name = map[int32]string{
		0: "RELAY_TRANSPORT_UNSPECIFIED",
		1: "RELAY_TRANSPORT_UDP",
		2: "RELAY_TRANSPORT_TCP",
		3: "RELAY_TRANSPORT_TLS",
	}
	RelayTransport_value = map[string]int32{
		"RELAY_TRANSPORT_UNSPECIFIED": 0,
		"RELAY_TRANSPORT_UDP":         1,
		"RELAY_TRANSPORT_TCP":         2,
		"RELAY_TRANSPORT_TLS":         3,
	}
)

func (x RelayTransport) Enum() *RelayTransport {
	p := new(RelayTransport)
	*p = x
	return p
}

func (x RelayTransport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayTransport) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_usage_proto_enumTypes[1].Descriptor()
}

func (RelayTransport) Type() protoreflect.EnumType {
	return &file_cloud_v1_usage_proto_enumTypes[1]
}

func (x RelayTransport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayTransport.Descriptor instead.
func (RelayTransport) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{1}
}

type RelaySettlementKind int32

const (
	RelaySettlementKind_RELAY_SETTLEMENT_KIND_UNSPECIFIED  RelaySettlementKind = 0
	RelaySettlementKind_RELAY_SETTLEMENT_KIND_EXACT        RelaySettlementKind = 1
	RelaySettlementKind_RELAY_SETTLEMENT_KIND_RECOVERY_MAX RelaySettlementKind = 2
)

// Enum value maps for RelaySettlementKind.
var (
	RelaySettlementKind_name = map[int32]string{
		0: "RELAY_SETTLEMENT_KIND_UNSPECIFIED",
		1: "RELAY_SETTLEMENT_KIND_EXACT",
		2: "RELAY_SETTLEMENT_KIND_RECOVERY_MAX",
	}
	RelaySettlementKind_value = map[string]int32{
		"RELAY_SETTLEMENT_KIND_UNSPECIFIED":  0,
		"RELAY_SETTLEMENT_KIND_EXACT":        1,
		"RELAY_SETTLEMENT_KIND_RECOVERY_MAX": 2,
	}
)

func (x RelaySettlementKind) Enum() *RelaySettlementKind {
	p := new(RelaySettlementKind)
	*p = x
	return p
}

func (x RelaySettlementKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelaySettlementKind) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_usage_proto_enumTypes[2].Descriptor()
}

func (RelaySettlementKind) Type() protoreflect.EnumType {
	return &file_cloud_v1_usage_proto_enumTypes[2]
}

func (x RelaySettlementKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelaySettlementKind.Descriptor instead.
func (RelaySettlementKind) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{2}
}

type RelayResponseCode int32

const (
	RelayResponseCode_RELAY_RESPONSE_CODE_UNSPECIFIED RelayResponseCode = 0
	RelayResponseCode_RELAY_RESPONSE_CODE_APPLIED     RelayResponseCode = 1
	RelayResponseCode_RELAY_RESPONSE_CODE_REPLAY      RelayResponseCode = 2
	RelayResponseCode_RELAY_RESPONSE_CODE_TERMINAL    RelayResponseCode = 3
	RelayResponseCode_RELAY_RESPONSE_CODE_REJECTED    RelayResponseCode = 4
	RelayResponseCode_RELAY_RESPONSE_CODE_CONFLICT    RelayResponseCode = 5
	RelayResponseCode_RELAY_RESPONSE_CODE_UNAVAILABLE RelayResponseCode = 6
)

// Enum value maps for RelayResponseCode.
var (
	RelayResponseCode_name = map[int32]string{
		0: "RELAY_RESPONSE_CODE_UNSPECIFIED",
		1: "RELAY_RESPONSE_CODE_APPLIED",
		2: "RELAY_RESPONSE_CODE_REPLAY",
		3: "RELAY_RESPONSE_CODE_TERMINAL",
		4: "RELAY_RESPONSE_CODE_REJECTED",
		5: "RELAY_RESPONSE_CODE_CONFLICT",
		6: "RELAY_RESPONSE_CODE_UNAVAILABLE",
	}
	RelayResponseCode_value = map[string]int32{
		"RELAY_RESPONSE_CODE_UNSPECIFIED": 0,
		"RELAY_RESPONSE_CODE_APPLIED":     1,
		"RELAY_RESPONSE_CODE_REPLAY":      2,
		"RELAY_RESPONSE_CODE_TERMINAL":    3,
		"RELAY_RESPONSE_CODE_REJECTED":    4,
		"RELAY_RESPONSE_CODE_CONFLICT":    5,
		"RELAY_RESPONSE_CODE_UNAVAILABLE": 6,
	}
)

func (x RelayResponseCode) Enum() *RelayResponseCode {
	p := new(RelayResponseCode)
	*p = x
	return p
}

func (x RelayResponseCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayResponseCode) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_usage_proto_enumTypes[3].Descriptor()
}

func (RelayResponseCode) Type() protoreflect.EnumType {
	return &file_cloud_v1_usage_proto_enumTypes[3]
}

func (x RelayResponseCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayResponseCode.Descriptor instead.
func (RelayResponseCode) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{3}
}

type RelayAccountActionType int32

const (
	RelayAccountActionType_RELAY_ACCOUNT_ACTION_TYPE_UNSPECIFIED    RelayAccountActionType = 0
	RelayAccountActionType_RELAY_ACCOUNT_ACTION_TYPE_ALLOW          RelayAccountActionType = 1
	RelayAccountActionType_RELAY_ACCOUNT_ACTION_TYPE_DENY_AND_CLOSE RelayAccountActionType = 2
)

// Enum value maps for RelayAccountActionType.
var (
	RelayAccountActionType_name = map[int32]string{
		0: "RELAY_ACCOUNT_ACTION_TYPE_UNSPECIFIED",
		1: "RELAY_ACCOUNT_ACTION_TYPE_ALLOW",
		2: "RELAY_ACCOUNT_ACTION_TYPE_DENY_AND_CLOSE",
	}
	RelayAccountActionType_value = map[string]int32{
		"RELAY_ACCOUNT_ACTION_TYPE_UNSPECIFIED":    0,
		"RELAY_ACCOUNT_ACTION_TYPE_ALLOW":          1,
		"RELAY_ACCOUNT_ACTION_TYPE_DENY_AND_CLOSE": 2,
	}
)

func (x RelayAccountActionType) Enum() *RelayAccountActionType {
	p := new(RelayAccountActionType)
	*p = x
	return p
}

func (x RelayAccountActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayAccountActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_usage_proto_enumTypes[4].Descriptor()
}

func (RelayAccountActionType) Type() protoreflect.EnumType {
	return &file_cloud_v1_usage_proto_enumTypes[4]
}

func (x RelayAccountActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayAccountActionType.Descriptor instead.
func (RelayAccountActionType) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{4}
}

type RelayJournalStage int32

const (
	RelayJournalStage_RELAY_JOURNAL_STAGE_UNSPECIFIED        RelayJournalStage = 0
	RelayJournalStage_RELAY_JOURNAL_STAGE_REQUESTED          RelayJournalStage = 1
	RelayJournalStage_RELAY_JOURNAL_STAGE_HELD_UNEXPOSED     RelayJournalStage = 2
	RelayJournalStage_RELAY_JOURNAL_STAGE_EXPOSED            RelayJournalStage = 3
	RelayJournalStage_RELAY_JOURNAL_STAGE_RENEW_PENDING      RelayJournalStage = 4
	RelayJournalStage_RELAY_JOURNAL_STAGE_CLOSING            RelayJournalStage = 5
	RelayJournalStage_RELAY_JOURNAL_STAGE_SETTLEMENT_DURABLE RelayJournalStage = 6
)

// Enum value maps for RelayJournalStage.
var (
	RelayJournalStage_name = map[int32]string{
		0: "RELAY_JOURNAL_STAGE_UNSPECIFIED",
		1: "RELAY_JOURNAL_STAGE_REQUESTED",
		2: "RELAY_JOURNAL_STAGE_HELD_UNEXPOSED",
		3: "RELAY_JOURNAL_STAGE_EXPOSED",
		4: "RELAY_JOURNAL_STAGE_RENEW_PENDING",
		5: "RELAY_JOURNAL_STAGE_CLOSING",
		6: "RELAY_JOURNAL_STAGE_SETTLEMENT_DURABLE",
	}
	RelayJournalStage_value = map[string]int32{
		"RELAY_JOURNAL_STAGE_UNSPECIFIED":        0,
		"RELAY_JOURNAL_STAGE_REQUESTED":          1,
		"RELAY_JOURNAL_STAGE_HELD_UNEXPOSED":     2,
		"RELAY_JOURNAL_STAGE_EXPOSED":            3,
		"RELAY_JOURNAL_STAGE_RENEW_PENDING":      4,
		"RELAY_JOURNAL_STAGE_CLOSING":            5,
		"RELAY_JOURNAL_STAGE_SETTLEMENT_DURABLE": 6,
	}
)

func (x RelayJournalStage) Enum() *RelayJournalStage {
	p := new(RelayJournalStage)
	*p = x
	return p
}

func (x RelayJournalStage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayJournalStage) Descriptor() protoreflect.EnumDescriptor {
	return file_cloud_v1_usage_proto_enumTypes[5].Descriptor()
}

func (RelayJournalStage) Type() protoreflect.EnumType {
	return &file_cloud_v1_usage_proto_enumTypes[5]
}

func (x RelayJournalStage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayJournalStage.Descriptor instead.
func (RelayJournalStage) EnumDescriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{5}
}

// RelayPolicySnapshot contains only inputs that actually authorize Relay.
// Both Controller and Edge hash its deterministic protobuf encoding.
type RelayPolicySnapshot struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	AccountId                  string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountRevision            uint64                 `protobuf:"varint,2,opt,name=account_revision,json=accountRevision,proto3" json:"account_revision,omitempty"`
	AccountState               string                 `protobuf:"bytes,3,opt,name=account_state,json=accountState,proto3" json:"account_state,omitempty"`
	SubscriptionId             string                 `protobuf:"bytes,4,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	SubscriptionRevision       uint64                 `protobuf:"varint,5,opt,name=subscription_revision,json=subscriptionRevision,proto3" json:"subscription_revision,omitempty"`
	SubscriptionState          string                 `protobuf:"bytes,6,opt,name=subscription_state,json=subscriptionState,proto3" json:"subscription_state,omitempty"`
	PeriodStart                *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd                  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	PlanId                     string                 `protobuf:"bytes,9,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	PlanVersion                uint64                 `protobuf:"varint,10,opt,name=plan_version,json=planVersion,proto3" json:"plan_version,omitempty"`
	PlanRevision               uint64                 `protobuf:"varint,11,opt,name=plan_revision,json=planRevision,proto3" json:"plan_revision,omitempty"`
	RelayEnabled               bool                   `protobuf:"varint,12,opt,name=relay_enabled,json=relayEnabled,proto3" json:"relay_enabled,omitempty"`
	RelayMaxBytesPerPeriod     uint64                 `protobuf:"varint,13,opt,name=relay_max_bytes_per_period,json=relayMaxBytesPerPeriod,proto3" json:"relay_max_bytes_per_period,omitempty"`
	RelayMaxBytesPerSession    uint64                 `protobuf:"varint,14,opt,name=relay_max_bytes_per_session,json=relayMaxBytesPerSession,proto3" json:"relay_max_bytes_per_session,omitempty"`
	RelayMaxRateBytesPerSecond uint64                 `protobuf:"varint,15,opt,name=relay_max_rate_bytes_per_second,json=relayMaxRateBytesPerSecond,proto3" json:"relay_max_rate_bytes_per_second,omitempty"`
	RelayMaxConcurrency        uint32                 `protobuf:"varint,16,opt,name=relay_max_concurrency,json=relayMaxConcurrency,proto3" json:"relay_max_concurrency,omitempty"`
	AllowedRegions             []string               `protobuf:"bytes,17,rep,name=allowed_regions,json=allowedRegions,proto3" json:"allowed_regions,omitempty"`
	EdgeId                     string                 `protobuf:"bytes,18,opt,name=edge_id,json=edgeId,proto3" json:"edge_id,omitempty"`
	EdgeRevision               uint64                 `protobuf:"varint,19,opt,name=edge_revision,json=edgeRevision,proto3" json:"edge_revision,omitempty"`
	EdgeEnabled                bool                   `protobuf:"varint,20,opt,name=edge_enabled,json=edgeEnabled,proto3" json:"edge_enabled,omitempty"`
	EdgeRegion                 string                 `protobuf:"bytes,21,opt,name=edge_region,json=edgeRegion,proto3" json:"edge_region,omitempty"`
	DaemonId                   string                 `protobuf:"bytes,22,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	DaemonStateRevision        uint64                 `protobuf:"varint,23,opt,name=daemon_state_revision,json=daemonStateRevision,proto3" json:"daemon_state_revision,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RelayPolicySnapshot) Reset() {
	*x = RelayPolicySnapshot{}
	mi := &file_cloud_v1_usage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayPolicySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayPolicySnapshot) ProtoMessage() {}

func (x *RelayPolicySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayPolicySnapshot.ProtoReflect.Descriptor instead.
func (*RelayPolicySnapshot) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{0}
}

func (x *RelayPolicySnapshot) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RelayPolicySnapshot) GetAccountRevision() uint64 {
	if x != nil {
		return x.AccountRevision
	}
	return 0
}

func (x *RelayPolicySnapshot) GetAccountState() string {
	if x != nil {
		return x.AccountState
	}
	return ""
}

func (x *RelayPolicySnapshot) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *RelayPolicySnapshot) GetSubscriptionRevision() uint64 {
	if x != nil {
		return x.SubscriptionRevision
	}
	return 0
}

func (x *RelayPolicySnapshot) GetSubscriptionState() string {
	if x != nil {
		return x.SubscriptionState
	}
	return ""
}

func (x *RelayPolicySnapshot) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *RelayPolicySnapshot) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *RelayPolicySnapshot) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *RelayPolicySnapshot) GetPlanVersion() uint64 {
	if x != nil {
		return x.PlanVersion
	}
	return 0
}

func (x *RelayPolicySnapshot) GetPlanRevision() uint64 {
	if x != nil {
		return x.PlanRevision
	}
	return 0
}

func (x *RelayPolicySnapshot) GetRelayEnabled() bool {
	if x != nil {
		return x.RelayEnabled
	}
	return false
}

func (x *RelayPolicySnapshot) GetRelayMaxBytesPerPeriod() uint64 {
	if x != nil {
		return x.RelayMaxBytesPerPeriod
	}
	return 0
}

func (x *RelayPolicySnapshot) GetRelayMaxBytesPerSession() uint64 {
	if x != nil {
		return x.RelayMaxBytesPerSession
	}
	return 0
}

func (x *RelayPolicySnapshot) GetRelayMaxRateBytesPerSecond() uint64 {
	if x != nil {
		return x.RelayMaxRateBytesPerSecond
	}
	return 0
}

func (x *RelayPolicySnapshot) GetRelayMaxConcurrency() uint32 {
	if x != nil {
		return x.RelayMaxConcurrency
	}
	return 0
}

func (x *RelayPolicySnapshot) GetAllowedRegions() []string {
	if x != nil {
		return x.AllowedRegions
	}
	return nil
}

func (x *RelayPolicySnapshot) GetEdgeId() string {
	if x != nil {
		return x.EdgeId
	}
	return ""
}

func (x *RelayPolicySnapshot) GetEdgeRevision() uint64 {
	if x != nil {
		return x.EdgeRevision
	}
	return 0
}

func (x *RelayPolicySnapshot) GetEdgeEnabled() bool {
	if x != nil {
		return x.EdgeEnabled
	}
	return false
}

func (x *RelayPolicySnapshot) GetEdgeRegion() string {
	if x != nil {
		return x.EdgeRegion
	}
	return ""
}

func (x *RelayPolicySnapshot) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *RelayPolicySnapshot) GetDaemonStateRevision() uint64 {
	if x != nil {
		return x.DaemonStateRevision
	}
	return 0
}

type RelayReserveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DaemonId      string                 `protobuf:"bytes,3,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,5,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	RequestDigest []byte                 `protobuf:"bytes,7,opt,name=request_digest,json=requestDigest,proto3" json:"request_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayReserveRequest) Reset() {
	*x = RelayReserveRequest{}
	mi := &file_cloud_v1_usage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayReserveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayReserveRequest) ProtoMessage() {}

func (x *RelayReserveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayReserveRequest.ProtoReflect.Descriptor instead.
func (*RelayReserveRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{1}
}

func (x *RelayReserveRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *RelayReserveRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RelayReserveRequest) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *RelayReserveRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RelayReserveRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RelayReserveRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *RelayReserveRequest) GetRequestDigest() []byte {
	if x != nil {
		return x.RequestDigest
	}
	return nil
}

type RelayGrant struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ReservationId         string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	SessionId             string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ReservedBytes         uint64                 `protobuf:"varint,3,opt,name=reserved_bytes,json=reservedBytes,proto3" json:"reserved_bytes,omitempty"`
	MaxRateBytesPerSecond uint64                 `protobuf:"varint,4,opt,name=max_rate_bytes_per_second,json=maxRateBytesPerSecond,proto3" json:"max_rate_bytes_per_second,omitempty"`
	RenewSequence         uint64                 `protobuf:"varint,5,opt,name=renew_sequence,json=renewSequence,proto3" json:"renew_sequence,omitempty"`
	AuthorizedUntil       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=authorized_until,json=authorizedUntil,proto3" json:"authorized_until,omitempty"`
	PolicyDigest          []byte                 `protobuf:"bytes,7,opt,name=policy_digest,json=policyDigest,proto3" json:"policy_digest,omitempty"`
	Policy                *RelayPolicySnapshot   `protobuf:"bytes,8,opt,name=policy,proto3" json:"policy,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RelayGrant) Reset() {
	*x = RelayGrant{}
	mi := &file_cloud_v1_usage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayGrant) ProtoMessage() {}

func (x *RelayGrant) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayGrant.ProtoReflect.Descriptor instead.
func (*RelayGrant) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{2}
}

func (x *RelayGrant) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *RelayGrant) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RelayGrant) GetReservedBytes() uint64 {
	if x != nil {
		return x.ReservedBytes
	}
	return 0
}

func (x *RelayGrant) GetMaxRateBytesPerSecond() uint64 {
	if x != nil {
		return x.MaxRateBytesPerSecond
	}
	return 0
}

func (x *RelayGrant) GetRenewSequence() uint64 {
	if x != nil {
		return x.RenewSequence
	}
	return 0
}

func (x *RelayGrant) GetAuthorizedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.AuthorizedUntil
	}
	return nil
}

func (x *RelayGrant) GetPolicyDigest() []byte {
	if x != nil {
		return x.PolicyDigest
	}
	return nil
}

func (x *RelayGrant) GetPolicy() *RelayPolicySnapshot {
	if x != nil {
		return x.Policy
	}
	return nil
}

type RelayReserveResponse struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	ReservationId      string                   `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	RequestDigest      []byte                   `protobuf:"bytes,2,opt,name=request_digest,json=requestDigest,proto3" json:"request_digest,omitempty"`
	Code               RelayResponseCode        `protobuf:"varint,3,opt,name=code,proto3,enum=anytty.cloud.v1.RelayResponseCode" json:"code,omitempty"`
	Grant              *RelayGrant              `protobuf:"bytes,4,opt,name=grant,proto3" json:"grant,omitempty"`
	Terminal           *RelaySettlementAck      `protobuf:"bytes,5,opt,name=terminal,proto3" json:"terminal,omitempty"`
	ErrorMessage       string                   `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	EntitlementFailure *CloudEntitlementFailure `protobuf:"bytes,7,opt,name=entitlement_failure,json=entitlementFailure,proto3" json:"entitlement_failure,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RelayReserveResponse) Reset() {
	*x = RelayReserveResponse{}
	mi := &file_cloud_v1_usage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayReserveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayReserveResponse) ProtoMessage() {}

func (x *RelayReserveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayReserveResponse.ProtoReflect.Descriptor instead.
func (*RelayReserveResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{3}
}

func (x *RelayReserveResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *RelayReserveResponse) GetRequestDigest() []byte {
	if x != nil {
		return x.RequestDigest
	}
	return nil
}

func (x *RelayReserveResponse) GetCode() RelayResponseCode {
	if x != nil {
		return x.Code
	}
	return RelayResponseCode_RELAY_RESPONSE_CODE_UNSPECIFIED
}

func (x *RelayReserveResponse) GetGrant() *RelayGrant {
	if x != nil {
		return x.Grant
	}
	return nil
}

func (x *RelayReserveResponse) GetTerminal() *RelaySettlementAck {
	if x != nil {
		return x.Terminal
	}
	return nil
}

func (x *RelayReserveResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RelayReserveResponse) GetEntitlementFailure() *CloudEntitlementFailure {
	if x != nil {
		return x.EntitlementFailure
	}
	return nil
}

type RelayRenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	RenewSequence uint64                 `protobuf:"varint,2,opt,name=renew_sequence,json=renewSequence,proto3" json:"renew_sequence,omitempty"`
	PolicyDigest  []byte                 `protobuf:"bytes,3,opt,name=policy_digest,json=policyDigest,proto3" json:"policy_digest,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayRenewRequest) Reset() {
	*x = RelayRenewRequest{}
	mi := &file_cloud_v1_usage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRenewRequest) ProtoMessage() {}

func (x *RelayRenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRenewRequest.ProtoReflect.Descriptor instead.
func (*RelayRenewRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{4}
}

func (x *RelayRenewRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *RelayRenewRequest) GetRenewSequence() uint64 {
	if x != nil {
		return x.RenewSequence
	}
	return 0
}

func (x *RelayRenewRequest) GetPolicyDigest() []byte {
	if x != nil {
		return x.PolicyDigest
	}
	return nil
}

func (x *RelayRenewRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type RelayRenewResponse struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	ReservationId      string                   `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	RenewSequence      uint64                   `protobuf:"varint,2,opt,name=renew_sequence,json=renewSequence,proto3" json:"renew_sequence,omitempty"`
	Code               RelayResponseCode        `protobuf:"varint,3,opt,name=code,proto3,enum=anytty.cloud.v1.RelayResponseCode" json:"code,omitempty"`
	Grant              *RelayGrant              `protobuf:"bytes,4,opt,name=grant,proto3" json:"grant,omitempty"`
	Terminal           *RelaySettlementAck      `protobuf:"bytes,5,opt,name=terminal,proto3" json:"terminal,omitempty"`
	ErrorMessage       string                   `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	EntitlementFailure *CloudEntitlementFailure `protobuf:"bytes,7,opt,name=entitlement_failure,json=entitlementFailure,proto3" json:"entitlement_failure,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RelayRenewResponse) Reset() {
	*x = RelayRenewResponse{}
	mi := &file_cloud_v1_usage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRenewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRenewResponse) ProtoMessage() {}

func (x *RelayRenewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRenewResponse.ProtoReflect.Descriptor instead.
func (*RelayRenewResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{5}
}

func (x *RelayRenewResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *RelayRenewResponse) GetRenewSequence() uint64 {
	if x != nil {
		return x.RenewSequence
	}
	return 0
}

func (x *RelayRenewResponse) GetCode() RelayResponseCode {
	if x != nil {
		return x.Code
	}
	return RelayResponseCode_RELAY_RESPONSE_CODE_UNSPECIFIED
}

func (x *RelayRenewResponse) GetGrant() *RelayGrant {
	if x != nil {
		return x.Grant
	}
	return nil
}

func (x *RelayRenewResponse) GetTerminal() *RelaySettlementAck {
	if x != nil {
		return x.Terminal
	}
	return nil
}

func (x *RelayRenewResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RelayRenewResponse) GetEntitlementFailure() *CloudEntitlementFailure {
	if x != nil {
		return x.EntitlementFailure
	}
	return nil
}

type RelaySettlement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Kind          RelaySettlementKind    `protobuf:"varint,2,opt,name=kind,proto3,enum=anytty.cloud.v1.RelaySettlementKind" json:"kind,omitempty"`
	IngressBytes  uint64                 `protobuf:"varint,3,opt,name=ingress_bytes,json=ingressBytes,proto3" json:"ingress_bytes,omitempty"`
	EgressBytes   uint64                 `protobuf:"varint,4,opt,name=egress_bytes,json=egressBytes,proto3" json:"egress_bytes,omitempty"`
	PolicyDigest  []byte                 `protobuf:"bytes,5,opt,name=policy_digest,json=policyDigest,proto3" json:"policy_digest,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelaySettlement) Reset() {
	*x = RelaySettlement{}
	mi := &file_cloud_v1_usage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelaySettlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelaySettlement) ProtoMessage() {}

func (x *RelaySettlement) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelaySettlement.ProtoReflect.Descriptor instead.
func (*RelaySettlement) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{6}
}

func (x *RelaySettlement) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *RelaySettlement) GetKind() RelaySettlementKind {
	if x != nil {
		return x.Kind
	}
	return RelaySettlementKind_RELAY_SETTLEMENT_KIND_UNSPECIFIED
}

func (x *RelaySettlement) GetIngressBytes() uint64 {
	if x != nil {
		return x.IngressBytes
	}
	return 0
}

func (x *RelaySettlement) GetEgressBytes() uint64 {
	if x != nil {
		return x.EgressBytes
	}
	return 0
}

func (x *RelaySettlement) GetPolicyDigest() []byte {
	if x != nil {
		return x.PolicyDigest
	}
	return nil
}

func (x *RelaySettlement) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type RelaySettlementAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Kind          RelaySettlementKind    `protobuf:"varint,2,opt,name=kind,proto3,enum=anytty.cloud.v1.RelaySettlementKind" json:"kind,omitempty"`
	IngressBytes  uint64                 `protobuf:"varint,3,opt,name=ingress_bytes,json=ingressBytes,proto3" json:"ingress_bytes,omitempty"`
	EgressBytes   uint64                 `protobuf:"varint,4,opt,name=egress_bytes,json=egressBytes,proto3" json:"egress_bytes,omitempty"`
	RecoveryBytes uint64                 `protobuf:"varint,5,opt,name=recovery_bytes,json=recoveryBytes,proto3" json:"recovery_bytes,omitempty"`
	PolicyDigest  []byte                 `protobuf:"bytes,6,opt,name=policy_digest,json=policyDigest,proto3" json:"policy_digest,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	SettledAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
	Code          RelayResponseCode      `protobuf:"varint,9,opt,name=code,proto3,enum=anytty.cloud.v1.RelayResponseCode" json:"code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelaySettlementAck) Reset() {
	*x = RelaySettlementAck{}
	mi := &file_cloud_v1_usage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelaySettlementAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelaySettlementAck) ProtoMessage() {}

func (x *RelaySettlementAck) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelaySettlementAck.ProtoReflect.Descriptor instead.
func (*RelaySettlementAck) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{7}
}

func (x *RelaySettlementAck) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *RelaySettlementAck) GetKind() RelaySettlementKind {
	if x != nil {
		return x.Kind
	}
	return RelaySettlementKind_RELAY_SETTLEMENT_KIND_UNSPECIFIED
}

func (x *RelaySettlementAck) GetIngressBytes() uint64 {
	if x != nil {
		return x.IngressBytes
	}
	return 0
}

func (x *RelaySettlementAck) GetEgressBytes() uint64 {
	if x != nil {
		return x.EgressBytes
	}
	return 0
}

func (x *RelaySettlementAck) GetRecoveryBytes() uint64 {
	if x != nil {
		return x.RecoveryBytes
	}
	return 0
}

func (x *RelaySettlementAck) GetPolicyDigest() []byte {
	if x != nil {
		return x.PolicyDigest
	}
	return nil
}

func (x *RelaySettlementAck) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *RelaySettlementAck) GetSettledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SettledAt
	}
	return nil
}

func (x *RelaySettlementAck) GetCode() RelayResponseCode {
	if x != nil {
		return x.Code
	}
	return RelayResponseCode_RELAY_RESPONSE_CODE_UNSPECIFIED
}

func (x *RelaySettlementAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RelayQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayQueryRequest) Reset() {
	*x = RelayQueryRequest{}
	mi := &file_cloud_v1_usage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayQueryRequest) ProtoMessage() {}

func (x *RelayQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayQueryRequest.ProtoReflect.Descriptor instead.
func (*RelayQueryRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{8}
}

func (x *RelayQueryRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type RelayQueryResponse struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	ReservationId      string                   `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Code               RelayResponseCode        `protobuf:"varint,2,opt,name=code,proto3,enum=anytty.cloud.v1.RelayResponseCode" json:"code,omitempty"`
	Grant              *RelayGrant              `protobuf:"bytes,3,opt,name=grant,proto3" json:"grant,omitempty"`
	Terminal           *RelaySettlementAck      `protobuf:"bytes,4,opt,name=terminal,proto3" json:"terminal,omitempty"`
	ErrorMessage       string                   `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	EntitlementFailure *CloudEntitlementFailure `protobuf:"bytes,6,opt,name=entitlement_failure,json=entitlementFailure,proto3" json:"entitlement_failure,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RelayQueryResponse) Reset() {
	*x = RelayQueryResponse{}
	mi := &file_cloud_v1_usage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayQueryResponse) ProtoMessage() {}

func (x *RelayQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayQueryResponse.ProtoReflect.Descriptor instead.
func (*RelayQueryResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{9}
}

func (x *RelayQueryResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *RelayQueryResponse) GetCode() RelayResponseCode {
	if x != nil {
		return x.Code
	}
	return RelayResponseCode_RELAY_RESPONSE_CODE_UNSPECIFIED
}

func (x *RelayQueryResponse) GetGrant() *RelayGrant {
	if x != nil {
		return x.Grant
	}
	return nil
}

func (x *RelayQueryResponse) GetTerminal() *RelaySettlementAck {
	if x != nil {
		return x.Terminal
	}
	return nil
}

func (x *RelayQueryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *RelayQueryResponse) GetEntitlementFailure() *CloudEntitlementFailure {
	if x != nil {
		return x.EntitlementFailure
	}
	return nil
}

// RelayRuntimePolicy is a versioned commercial policy snapshot used by an
// Edge for local Relay admission. It does not reserve bytes or require renewal.
type RelayRuntimePolicy struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	AccountId                  string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	SubscriptionId             string                 `protobuf:"bytes,2,opt,name=subscription_id,json=subscriptionId,proto3" json:"subscription_id,omitempty"`
	PlanId                     string                 `protobuf:"bytes,3,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	PolicyRevision             uint64                 `protobuf:"varint,4,opt,name=policy_revision,json=policyRevision,proto3" json:"policy_revision,omitempty"`
	RelayEnabled               bool                   `protobuf:"varint,5,opt,name=relay_enabled,json=relayEnabled,proto3" json:"relay_enabled,omitempty"`
	RelayMaxRateBytesPerSecond uint64                 `protobuf:"varint,6,opt,name=relay_max_rate_bytes_per_second,json=relayMaxRateBytesPerSecond,proto3" json:"relay_max_rate_bytes_per_second,omitempty"`
	RelayMaxConcurrency        uint32                 `protobuf:"varint,7,opt,name=relay_max_concurrency,json=relayMaxConcurrency,proto3" json:"relay_max_concurrency,omitempty"`
	RelayQuotaBytes            uint64                 `protobuf:"varint,8,opt,name=relay_quota_bytes,json=relayQuotaBytes,proto3" json:"relay_quota_bytes,omitempty"`
	PeriodStart                *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd                  *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	AccountRevision            uint64                 `protobuf:"varint,11,opt,name=account_revision,json=accountRevision,proto3" json:"account_revision,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *RelayRuntimePolicy) Reset() {
	*x = RelayRuntimePolicy{}
	mi := &file_cloud_v1_usage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayRuntimePolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayRuntimePolicy) ProtoMessage() {}

func (x *RelayRuntimePolicy) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayRuntimePolicy.ProtoReflect.Descriptor instead.
func (*RelayRuntimePolicy) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{10}
}

func (x *RelayRuntimePolicy) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RelayRuntimePolicy) GetSubscriptionId() string {
	if x != nil {
		return x.SubscriptionId
	}
	return ""
}

func (x *RelayRuntimePolicy) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *RelayRuntimePolicy) GetPolicyRevision() uint64 {
	if x != nil {
		return x.PolicyRevision
	}
	return 0
}

func (x *RelayRuntimePolicy) GetRelayEnabled() bool {
	if x != nil {
		return x.RelayEnabled
	}
	return false
}

func (x *RelayRuntimePolicy) GetRelayMaxRateBytesPerSecond() uint64 {
	if x != nil {
		return x.RelayMaxRateBytesPerSecond
	}
	return 0
}

func (x *RelayRuntimePolicy) GetRelayMaxConcurrency() uint32 {
	if x != nil {
		return x.RelayMaxConcurrency
	}
	return 0
}

func (x *RelayRuntimePolicy) GetRelayQuotaBytes() uint64 {
	if x != nil {
		return x.RelayQuotaBytes
	}
	return 0
}

func (x *RelayRuntimePolicy) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *RelayRuntimePolicy) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *RelayRuntimePolicy) GetAccountRevision() uint64 {
	if x != nil {
		return x.AccountRevision
	}
	return 0
}

// RelayAuthorizeRequest is the optional fast-path cache fill used when an Edge
// has no local account policy. It never creates a durable reservation.
type RelayAuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	DaemonId      string                 `protobuf:"bytes,3,opt,name=daemon_id,json=daemonId,proto3" json:"daemon_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ObservedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayAuthorizeRequest) Reset() {
	*x = RelayAuthorizeRequest{}
	mi := &file_cloud_v1_usage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayAuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayAuthorizeRequest) ProtoMessage() {}

func (x *RelayAuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayAuthorizeRequest.ProtoReflect.Descriptor instead.
func (*RelayAuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{11}
}

func (x *RelayAuthorizeRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RelayAuthorizeRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RelayAuthorizeRequest) GetDaemonId() string {
	if x != nil {
		return x.DaemonId
	}
	return ""
}

func (x *RelayAuthorizeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RelayAuthorizeRequest) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

type RelayAuthorizeResponse struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	RequestId          string                   `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Policy             *RelayRuntimePolicy      `protobuf:"bytes,2,opt,name=policy,proto3" json:"policy,omitempty"`
	EntitlementFailure *CloudEntitlementFailure `protobuf:"bytes,3,opt,name=entitlement_failure,json=entitlementFailure,proto3" json:"entitlement_failure,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RelayAuthorizeResponse) Reset() {
	*x = RelayAuthorizeResponse{}
	mi := &file_cloud_v1_usage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayAuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayAuthorizeResponse) ProtoMessage() {}

func (x *RelayAuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayAuthorizeResponse.ProtoReflect.Descriptor instead.
func (*RelayAuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{12}
}

func (x *RelayAuthorizeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RelayAuthorizeResponse) GetPolicy() *RelayRuntimePolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *RelayAuthorizeResponse) GetEntitlementFailure() *CloudEntitlementFailure {
	if x != nil {
		return x.EntitlementFailure
	}
	return nil
}

// RelayUsageSample is cumulative for one (Edge boot, account) counter epoch.
// Retrying the same or an older value is therefore idempotent.
type RelayUsageSample struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccountId             string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	CumulativeEgressBytes uint64                 `protobuf:"varint,2,opt,name=cumulative_egress_bytes,json=cumulativeEgressBytes,proto3" json:"cumulative_egress_bytes,omitempty"`
	SampledAt             *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=sampled_at,json=sampledAt,proto3" json:"sampled_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RelayUsageSample) Reset() {
	*x = RelayUsageSample{}
	mi := &file_cloud_v1_usage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayUsageSample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayUsageSample) ProtoMessage() {}

func (x *RelayUsageSample) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayUsageSample.ProtoReflect.Descriptor instead.
func (*RelayUsageSample) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{13}
}

func (x *RelayUsageSample) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RelayUsageSample) GetCumulativeEgressBytes() uint64 {
	if x != nil {
		return x.CumulativeEgressBytes
	}
	return 0
}

func (x *RelayUsageSample) GetSampledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SampledAt
	}
	return nil
}

type RelayUsageBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchSequence uint64                 `protobuf:"varint,1,opt,name=batch_sequence,json=batchSequence,proto3" json:"batch_sequence,omitempty"`
	Samples       []*RelayUsageSample    `protobuf:"bytes,2,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayUsageBatch) Reset() {
	*x = RelayUsageBatch{}
	mi := &file_cloud_v1_usage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayUsageBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayUsageBatch) ProtoMessage() {}

func (x *RelayUsageBatch) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayUsageBatch.ProtoReflect.Descriptor instead.
func (*RelayUsageBatch) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{14}
}

func (x *RelayUsageBatch) GetBatchSequence() uint64 {
	if x != nil {
		return x.BatchSequence
	}
	return 0
}

func (x *RelayUsageBatch) GetSamples() []*RelayUsageSample {
	if x != nil {
		return x.Samples
	}
	return nil
}

type RelayAccountAction struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountId       string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Action          RelayAccountActionType `protobuf:"varint,2,opt,name=action,proto3,enum=anytty.cloud.v1.RelayAccountActionType" json:"action,omitempty"`
	ActionRevision  uint64                 `protobuf:"varint,3,opt,name=action_revision,json=actionRevision,proto3" json:"action_revision,omitempty"`
	UsedBytes       uint64                 `protobuf:"varint,4,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	QuotaBytes      uint64                 `protobuf:"varint,5,opt,name=quota_bytes,json=quotaBytes,proto3" json:"quota_bytes,omitempty"`
	PeriodStart     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=period_start,json=periodStart,proto3" json:"period_start,omitempty"`
	PeriodEnd       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=period_end,json=periodEnd,proto3" json:"period_end,omitempty"`
	Reason          string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	PolicyRevision  uint64                 `protobuf:"varint,9,opt,name=policy_revision,json=policyRevision,proto3" json:"policy_revision,omitempty"`
	AccountRevision uint64                 `protobuf:"varint,10,opt,name=account_revision,json=accountRevision,proto3" json:"account_revision,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RelayAccountAction) Reset() {
	*x = RelayAccountAction{}
	mi := &file_cloud_v1_usage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayAccountAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayAccountAction) ProtoMessage() {}

func (x *RelayAccountAction) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayAccountAction.ProtoReflect.Descriptor instead.
func (*RelayAccountAction) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{15}
}

func (x *RelayAccountAction) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RelayAccountAction) GetAction() RelayAccountActionType {
	if x != nil {
		return x.Action
	}
	return RelayAccountActionType_RELAY_ACCOUNT_ACTION_TYPE_UNSPECIFIED
}

func (x *RelayAccountAction) GetActionRevision() uint64 {
	if x != nil {
		return x.ActionRevision
	}
	return 0
}

func (x *RelayAccountAction) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *RelayAccountAction) GetQuotaBytes() uint64 {
	if x != nil {
		return x.QuotaBytes
	}
	return 0
}

func (x *RelayAccountAction) GetPeriodStart() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodStart
	}
	return nil
}

func (x *RelayAccountAction) GetPeriodEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.PeriodEnd
	}
	return nil
}

func (x *RelayAccountAction) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RelayAccountAction) GetPolicyRevision() uint64 {
	if x != nil {
		return x.PolicyRevision
	}
	return 0
}

func (x *RelayAccountAction) GetAccountRevision() uint64 {
	if x != nil {
		return x.AccountRevision
	}
	return 0
}

type RelayUsageAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatchSequence uint64                 `protobuf:"varint,1,opt,name=batch_sequence,json=batchSequence,proto3" json:"batch_sequence,omitempty"`
	Actions       []*RelayAccountAction  `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	ProcessedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=processed_at,json=processedAt,proto3" json:"processed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayUsageAck) Reset() {
	*x = RelayUsageAck{}
	mi := &file_cloud_v1_usage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayUsageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayUsageAck) ProtoMessage() {}

func (x *RelayUsageAck) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayUsageAck.ProtoReflect.Descriptor instead.
func (*RelayUsageAck) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{16}
}

func (x *RelayUsageAck) GetBatchSequence() uint64 {
	if x != nil {
		return x.BatchSequence
	}
	return 0
}

func (x *RelayUsageAck) GetActions() []*RelayAccountAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *RelayUsageAck) GetProcessedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ProcessedAt
	}
	return nil
}

// RelayICEConfig is derived from a committed Controller grant. It is durable
// before leaving the Edge and never contains commercial authority of its own.
type RelayICEConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	Urls          []string               `protobuf:"bytes,2,rep,name=urls,proto3" json:"urls,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Credential    string                 `protobuf:"bytes,4,opt,name=credential,proto3" json:"credential,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayICEConfig) Reset() {
	*x = RelayICEConfig{}
	mi := &file_cloud_v1_usage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayICEConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayICEConfig) ProtoMessage() {}

func (x *RelayICEConfig) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayICEConfig.ProtoReflect.Descriptor instead.
func (*RelayICEConfig) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{17}
}

func (x *RelayICEConfig) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *RelayICEConfig) GetUrls() []string {
	if x != nil {
		return x.Urls
	}
	return nil
}

func (x *RelayICEConfig) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RelayICEConfig) GetCredential() string {
	if x != nil {
		return x.Credential
	}
	return ""
}

func (x *RelayICEConfig) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// RelayJournalRecord is the single durable bbolt value for one reservation.
type RelayJournalRecord struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SchemaVersion        uint32                 `protobuf:"varint,1,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Stage                RelayJournalStage      `protobuf:"varint,2,opt,name=stage,proto3,enum=anytty.cloud.v1.RelayJournalStage" json:"stage,omitempty"`
	ReserveRequest       *RelayReserveRequest   `protobuf:"bytes,3,opt,name=reserve_request,json=reserveRequest,proto3" json:"reserve_request,omitempty"`
	Grant                *RelayGrant            `protobuf:"bytes,4,opt,name=grant,proto3" json:"grant,omitempty"`
	PendingRenewSequence uint64                 `protobuf:"varint,5,opt,name=pending_renew_sequence,json=pendingRenewSequence,proto3" json:"pending_renew_sequence,omitempty"`
	Settlement           *RelaySettlement       `protobuf:"bytes,6,opt,name=settlement,proto3" json:"settlement,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RelayJournalRecord) Reset() {
	*x = RelayJournalRecord{}
	mi := &file_cloud_v1_usage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayJournalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayJournalRecord) ProtoMessage() {}

func (x *RelayJournalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cloud_v1_usage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayJournalRecord.ProtoReflect.Descriptor instead.
func (*RelayJournalRecord) Descriptor() ([]byte, []int) {
	return file_cloud_v1_usage_proto_rawDescGZIP(), []int{18}
}

func (x *RelayJournalRecord) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *RelayJournalRecord) GetStage() RelayJournalStage {
	if x != nil {
		return x.Stage
	}
	return RelayJournalStage_RELAY_JOURNAL_STAGE_UNSPECIFIED
}

func (x *RelayJournalRecord) GetReserveRequest() *RelayReserveRequest {
	if x != nil {
		return x.ReserveRequest
	}
	return nil
}

func (x *RelayJournalRecord) GetGrant() *RelayGrant {
	if x != nil {
		return x.Grant
	}
	return nil
}

func (x *RelayJournalRecord) GetPendingRenewSequence() uint64 {
	if x != nil {
		return x.PendingRenewSequence
	}
	return 0
}

func (x *RelayJournalRecord) GetSettlement() *RelaySettlement {
	if x != nil {
		return x.Settlement
	}
	return nil
}

var File_cloud_v1_usage_proto protoreflect.FileDescriptor

const file_cloud_v1_usage_proto_rawDesc = "" +
	"\n" +
	"\x14cloud/v1/usage.proto\x12\x0fanytty.cloud.v1\x1a\x15cloud/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\b\n" +
	"\x13RelayPolicySnapshot\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12)\n" +
	"\x10account_revision\x18\x02 \x01(\x04R\x0faccountRevision\x12#\n" +
	"\raccount_state\x18\x03 \x01(\tR\faccountState\x12'\n" +
	"\x0fsubscription_id\x18\x04 \x01(\tR\x0esubscriptionId\x123\n" +
	"\x15subscription_revision\x18\x05 \x01(\x04R\x14subscriptionRevision\x12-\n" +
	"\x12subscription_state\x18\x06 \x01(\tR\x11subscriptionState\x12=\n" +
	"\fperiod_start\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12\x17\n" +
	"\aplan_id\x18\t \x01(\tR\x06planId\x12!\n" +
	"\fplan_version\x18\n" +
	" \x01(\x04R\vplanVersion\x12#\n" +
	"\rplan_revision\x18\v \x01(\x04R\fplanRevision\x12#\n" +
	"\rrelay_enabled\x18\f \x01(\bR\frelayEnabled\x12:\n" +
	"\x1arelay_max_bytes_per_period\x18\r \x01(\x04R\x16relayMaxBytesPerPeriod\x12<\n" +
	"\x1brelay_max_bytes_per_session\x18\x0e \x01(\x04R\x17relayMaxBytesPerSession\x12C\n" +
	"\x1frelay_max_rate_bytes_per_second\x18\x0f \x01(\x04R\x1arelayMaxRateBytesPerSecond\x122\n" +
	"\x15relay_max_concurrency\x18\x10 \x01(\rR\x13relayMaxConcurrency\x12'\n" +
	"\x0fallowed_regions\x18\x11 \x03(\tR\x0eallowedRegions\x12\x17\n" +
	"\aedge_id\x18\x12 \x01(\tR\x06edgeId\x12#\n" +
	"\redge_revision\x18\x13 \x01(\x04R\fedgeRevision\x12!\n" +
	"\fedge_enabled\x18\x14 \x01(\bR\vedgeEnabled\x12\x1f\n" +
	"\vedge_region\x18\x15 \x01(\tR\n" +
	"edgeRegion\x12\x1b\n" +
	"\tdaemon_id\x18\x16 \x01(\tR\bdaemonId\x122\n" +
	"\x15daemon_state_revision\x18\x17 \x01(\x04R\x13daemonStateRevisionJ\x04\b\x18\x10\x1d\"\x98\x02\n" +
	"\x13RelayReserveRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1b\n" +
	"\tdaemon_id\x18\x03 \x01(\tR\bdaemonId\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x05 \x01(\tR\tsessionId\x12;\n" +
	"\vobserved_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12%\n" +
	"\x0erequest_digest\x18\a \x01(\fR\rrequestDigest\"\x84\x03\n" +
	"\n" +
	"RelayGrant\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12%\n" +
	"\x0ereserved_bytes\x18\x03 \x01(\x04R\rreservedBytes\x128\n" +
	"\x19max_rate_bytes_per_second\x18\x04 \x01(\x04R\x15maxRateBytesPerSecond\x12%\n" +
	"\x0erenew_sequence\x18\x05 \x01(\x04R\rrenewSequence\x12E\n" +
	"\x10authorized_until\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0fauthorizedUntil\x12#\n" +
	"\rpolicy_digest\x18\a \x01(\fR\fpolicyDigest\x12<\n" +
	"\x06policy\x18\b \x01(\v2$.anytty.cloud.v1.RelayPolicySnapshotR\x06policy\"\x90\x03\n" +
	"\x14RelayReserveResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12%\n" +
	"\x0erequest_digest\x18\x02 \x01(\fR\rrequestDigest\x126\n" +
	"\x04code\x18\x03 \x01(\x0e2\".anytty.cloud.v1.RelayResponseCodeR\x04code\x121\n" +
	"\x05grant\x18\x04 \x01(\v2\x1b.anytty.cloud.v1.RelayGrantR\x05grant\x12?\n" +
	"\bterminal\x18\x05 \x01(\v2#.anytty.cloud.v1.RelaySettlementAckR\bterminal\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12Y\n" +
	"\x13entitlement_failure\x18\a \x01(\v2(.anytty.cloud.v1.CloudEntitlementFailureR\x12entitlementFailure\"\xc3\x01\n" +
	"\x11RelayRenewRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12%\n" +
	"\x0erenew_sequence\x18\x02 \x01(\x04R\rrenewSequence\x12#\n" +
	"\rpolicy_digest\x18\x03 \x01(\fR\fpolicyDigest\x12;\n" +
	"\vobserved_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"\x8e\x03\n" +
	"\x12RelayRenewResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12%\n" +
	"\x0erenew_sequence\x18\x02 \x01(\x04R\rrenewSequence\x126\n" +
	"\x04code\x18\x03 \x01(\x0e2\".anytty.cloud.v1.RelayResponseCodeR\x04code\x121\n" +
	"\x05grant\x18\x04 \x01(\v2\x1b.anytty.cloud.v1.RelayGrantR\x05grant\x12?\n" +
	"\bterminal\x18\x05 \x01(\v2#.anytty.cloud.v1.RelaySettlementAckR\bterminal\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12Y\n" +
	"\x13entitlement_failure\x18\a \x01(\v2(.anytty.cloud.v1.CloudEntitlementFailureR\x12entitlementFailure\"\x9c\x02\n" +
	"\x0fRelaySettlement\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x128\n" +
	"\x04kind\x18\x02 \x01(\x0e2$.anytty.cloud.v1.RelaySettlementKindR\x04kind\x12#\n" +
	"\ringress_bytes\x18\x03 \x01(\x04R\fingressBytes\x12!\n" +
	"\fegress_bytes\x18\x04 \x01(\x04R\vegressBytes\x12#\n" +
	"\rpolicy_digest\x18\x05 \x01(\fR\fpolicyDigest\x12;\n" +
	"\vobserved_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"\xde\x03\n" +
	"\x12RelaySettlementAck\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x128\n" +
	"\x04kind\x18\x02 \x01(\x0e2$.anytty.cloud.v1.RelaySettlementKindR\x04kind\x12#\n" +
	"\ringress_bytes\x18\x03 \x01(\x04R\fingressBytes\x12!\n" +
	"\fegress_bytes\x18\x04 \x01(\x04R\vegressBytes\x12%\n" +
	"\x0erecovery_bytes\x18\x05 \x01(\x04R\rrecoveryBytes\x12#\n" +
	"\rpolicy_digest\x18\x06 \x01(\fR\fpolicyDigest\x12;\n" +
	"\vobserved_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x129\n" +
	"\n" +
	"settled_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tsettledAt\x126\n" +
	"\x04code\x18\t \x01(\x0e2\".anytty.cloud.v1.RelayResponseCodeR\x04code\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\":\n" +
	"\x11RelayQueryRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"\xe7\x02\n" +
	"\x12RelayQueryResponse\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x126\n" +
	"\x04code\x18\x02 \x01(\x0e2\".anytty.cloud.v1.RelayResponseCodeR\x04code\x121\n" +
	"\x05grant\x18\x03 \x01(\v2\x1b.anytty.cloud.v1.RelayGrantR\x05grant\x12?\n" +
	"\bterminal\x18\x04 \x01(\v2#.anytty.cloud.v1.RelaySettlementAckR\bterminal\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12Y\n" +
	"\x13entitlement_failure\x18\x06 \x01(\v2(.anytty.cloud.v1.CloudEntitlementFailureR\x12entitlementFailure\"\x8d\x04\n" +
	"\x12RelayRuntimePolicy\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12'\n" +
	"\x0fsubscription_id\x18\x02 \x01(\tR\x0esubscriptionId\x12\x17\n" +
	"\aplan_id\x18\x03 \x01(\tR\x06planId\x12'\n" +
	"\x0fpolicy_revision\x18\x04 \x01(\x04R\x0epolicyRevision\x12#\n" +
	"\rrelay_enabled\x18\x05 \x01(\bR\frelayEnabled\x12C\n" +
	"\x1frelay_max_rate_bytes_per_second\x18\x06 \x01(\x04R\x1arelayMaxRateBytesPerSecond\x122\n" +
	"\x15relay_max_concurrency\x18\a \x01(\rR\x13relayMaxConcurrency\x12*\n" +
	"\x11relay_quota_bytes\x18\b \x01(\x04R\x0frelayQuotaBytes\x12=\n" +
	"\fperiod_start\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12)\n" +
	"\x10account_revision\x18\v \x01(\x04R\x0faccountRevision\"\xce\x01\n" +
	"\x15RelayAuthorizeRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\taccountId\x12\x1b\n" +
	"\tdaemon_id\x18\x03 \x01(\tR\bdaemonId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12;\n" +
	"\vobserved_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\"\xcf\x01\n" +
	"\x16RelayAuthorizeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12;\n" +
	"\x06policy\x18\x02 \x01(\v2#.anytty.cloud.v1.RelayRuntimePolicyR\x06policy\x12Y\n" +
	"\x13entitlement_failure\x18\x03 \x01(\v2(.anytty.cloud.v1.CloudEntitlementFailureR\x12entitlementFailure\"\xa4\x01\n" +
	"\x10RelayUsageSample\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x126\n" +
	"\x17cumulative_egress_bytes\x18\x02 \x01(\x04R\x15cumulativeEgressBytes\x129\n" +
	"\n" +
	"sampled_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tsampledAt\"u\n" +
	"\x0fRelayUsageBatch\x12%\n" +
	"\x0ebatch_sequence\x18\x01 \x01(\x04R\rbatchSequence\x12;\n" +
	"\asamples\x18\x02 \x03(\v2!.anytty.cloud.v1.RelayUsageSampleR\asamples\"\xc3\x03\n" +
	"\x12RelayAccountAction\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12?\n" +
	"\x06action\x18\x02 \x01(\x0e2'.anytty.cloud.v1.RelayAccountActionTypeR\x06action\x12'\n" +
	"\x0faction_revision\x18\x03 \x01(\x04R\x0eactionRevision\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x04 \x01(\x04R\tusedBytes\x12\x1f\n" +
	"\vquota_bytes\x18\x05 \x01(\x04R\n" +
	"quotaBytes\x12=\n" +
	"\fperiod_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vperiodStart\x129\n" +
	"\n" +
	"period_end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tperiodEnd\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12'\n" +
	"\x0fpolicy_revision\x18\t \x01(\x04R\x0epolicyRevision\x12)\n" +
	"\x10account_revision\x18\n" +
	" \x01(\x04R\x0faccountRevision\"\xb4\x01\n" +
	"\rRelayUsageAck\x12%\n" +
	"\x0ebatch_sequence\x18\x01 \x01(\x04R\rbatchSequence\x12=\n" +
	"\aactions\x18\x02 \x03(\v2#.anytty.cloud.v1.RelayAccountActionR\aactions\x12=\n" +
	"\fprocessed_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vprocessedAt\"\xc2\x01\n" +
	"\x0eRelayICEConfig\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x12\n" +
	"\x04urls\x18\x02 \x03(\tR\x04urls\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x1e\n" +
	"\n" +
	"credential\x18\x04 \x01(\tR\n" +
	"credential\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xef\x02\n" +
	"\x12RelayJournalRecord\x12%\n" +
	"\x0eschema_version\x18\x01 \x01(\rR\rschemaVersion\x128\n" +
	"\x05stage\x18\x02 \x01(\x0e2\".anytty.cloud.v1.RelayJournalStageR\x05stage\x12M\n" +
	"\x0freserve_request\x18\x03 \x01(\v2$.anytty.cloud.v1.RelayReserveRequestR\x0ereserveRequest\x121\n" +
	"\x05grant\x18\x04 \x01(\v2\x1b.anytty.cloud.v1.RelayGrantR\x05grant\x124\n" +
	"\x16pending_renew_sequence\x18\x05 \x01(\x04R\x14pendingRenewSequence\x12@\n" +
	"\n" +
	"settlement\x18\x06 \x01(\v2 .anytty.cloud.v1.RelaySettlementR\n" +
	"settlement*\x91\x01\n" +
	"\x0fRelayPreference\x12 \n" +
	"\x1cRELAY_PREFERENCE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RELAY_PREFERENCE_AUTO\x10\x01\x12 \n" +
	"\x1cRELAY_PREFERENCE_DIRECT_ONLY\x10\x02\x12\x1f\n" +
	"\x1bRELAY_PREFERENCE_RELAY_ONLY\x10\x03*|\n" +
	"\x0eRelayTransport\x12\x1f\n" +
	"\x1bRELAY_TRANSPORT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RELAY_TRANSPORT_UDP\x10\x01\x12\x17\n" +
	"\x13RELAY_TRANSPORT_TCP\x10\x02\x12\x17\n" +
	"\x13RELAY_TRANSPORT_TLS\x10\x03*\x85\x01\n" +
	"\x13RelaySettlementKind\x12%\n" +
	"!RELAY_SETTLEMENT_KIND_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bRELAY_SETTLEMENT_KIND_EXACT\x10\x01\x12&\n" +
	"\"RELAY_SETTLEMENT_KIND_RECOVERY_MAX\x10\x02*\x84\x02\n" +
	"\x11RelayResponseCode\x12#\n" +
	"\x1fRELAY_RESPONSE_CODE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bRELAY_RESPONSE_CODE_APPLIED\x10\x01\x12\x1e\n" +
	"\x1aRELAY_RESPONSE_CODE_REPLAY\x10\x02\x12 \n" +
	"\x1cRELAY_RESPONSE_CODE_TERMINAL\x10\x03\x12 \n" +
	"\x1cRELAY_RESPONSE_CODE_REJECTED\x10\x04\x12 \n" +
	"\x1cRELAY_RESPONSE_CODE_CONFLICT\x10\x05\x12#\n" +
	"\x1fRELAY_RESPONSE_CODE_UNAVAILABLE\x10\x06*\x96\x01\n" +
	"\x16RelayAccountActionType\x12)\n" +
	"%RELAY_ACCOUNT_ACTION_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fRELAY_ACCOUNT_ACTION_TYPE_ALLOW\x10\x01\x12,\n" +
	"(RELAY_ACCOUNT_ACTION_TYPE_DENY_AND_CLOSE\x10\x02*\x98\x02\n" +
	"\x11RelayJournalStage\x12#\n" +
	"\x1fRELAY_JOURNAL_STAGE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dRELAY_JOURNAL_STAGE_REQUESTED\x10\x01\x12&\n" +
	"\"RELAY_JOURNAL_STAGE_HELD_UNEXPOSED\x10\x02\x12\x1f\n" +
	"\x1bRELAY_JOURNAL_STAGE_EXPOSED\x10\x03\x12%\n" +
	"!RELAY_JOURNAL_STAGE_RENEW_PENDING\x10\x04\x12\x1f\n" +
	"\x1bRELAY_JOURNAL_STAGE_CLOSING\x10\x05\x12*\n" +
	"&RELAY_JOURNAL_STAGE_SETTLEMENT_DURABLE\x10\x06B1Z/github.com/anytty/anytty/proto/cloud/v1;cloudv1b\x06proto3"

var (
	file_cloud_v1_usage_proto_rawDescOnce sync.Once
	file_cloud_v1_usage_proto_rawDescData []byte
)

func file_cloud_v1_usage_proto_rawDescGZIP() []byte {
	file_cloud_v1_usage_proto_rawDescOnce.Do(func() {
		file_cloud_v1_usage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cloud_v1_usage_proto_rawDesc), len(file_cloud_v1_usage_proto_rawDesc)))
	})
	return file_cloud_v1_usage_proto_rawDescData
}

var file_cloud_v1_usage_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_cloud_v1_usage_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_cloud_v1_usage_proto_goTypes = []any{
	(RelayPreference)(0),            // 0: anytty.cloud.v1.RelayPreference
	(RelayTransport)(0),             // 1: anytty.cloud.v1.RelayTransport
	(RelaySettlementKind)(0),        // 2: anytty.cloud.v1.RelaySettlementKind
	(RelayResponseCode)(0),          // 3: anytty.cloud.v1.RelayResponseCode
	(RelayAccountActionType)(0),     // 4: anytty.cloud.v1.RelayAccountActionType
	(RelayJournalStage)(0),          // 5: anytty.cloud.v1.RelayJournalStage
	(*RelayPolicySnapshot)(nil),     // 6: anytty.cloud.v1.RelayPolicySnapshot
	(*RelayReserveRequest)(nil),     // 7: anytty.cloud.v1.RelayReserveRequest
	(*RelayGrant)(nil),              // 8: anytty.cloud.v1.RelayGrant
	(*RelayReserveResponse)(nil),    // 9: anytty.cloud.v1.RelayReserveResponse
	(*RelayRenewRequest)(nil),       // 10: anytty.cloud.v1.RelayRenewRequest
	(*RelayRenewResponse)(nil),      // 11: anytty.cloud.v1.RelayRenewResponse
	(*RelaySettlement)(nil),         // 12: anytty.cloud.v1.RelaySettlement
	(*RelaySettlementAck)(nil),      // 13: anytty.cloud.v1.RelaySettlementAck
	(*RelayQueryRequest)(nil),       // 14: anytty.cloud.v1.RelayQueryRequest
	(*RelayQueryResponse)(nil),      // 15: anytty.cloud.v1.RelayQueryResponse
	(*RelayRuntimePolicy)(nil),      // 16: anytty.cloud.v1.RelayRuntimePolicy
	(*RelayAuthorizeRequest)(nil),   // 17: anytty.cloud.v1.RelayAuthorizeRequest
	(*RelayAuthorizeResponse)(nil),  // 18: anytty.cloud.v1.RelayAuthorizeResponse
	(*RelayUsageSample)(nil),        // 19: anytty.cloud.v1.RelayUsageSample
	(*RelayUsageBatch)(nil),         // 20: anytty.cloud.v1.RelayUsageBatch
	(*RelayAccountAction)(nil),      // 21: anytty.cloud.v1.RelayAccountAction
	(*RelayUsageAck)(nil),           // 22: anytty.cloud.v1.RelayUsageAck
	(*RelayICEConfig)(nil),          // 23: anytty.cloud.v1.RelayICEConfig
	(*RelayJournalRecord)(nil),      // 24: anytty.cloud.v1.RelayJournalRecord
	(*timestamppb.Timestamp)(nil),   // 25: google.protobuf.Timestamp
	(*CloudEntitlementFailure)(nil), // 26: anytty.cloud.v1.CloudEntitlementFailure
}
var file_cloud_v1_usage_proto_depIdxs = []int32{
	25, // 0: anytty.cloud.v1.RelayPolicySnapshot.period_start:type_name -> google.protobuf.Timestamp
	25, // 1: anytty.cloud.v1.RelayPolicySnapshot.period_end:type_name -> google.protobuf.Timestamp
	25, // 2: anytty.cloud.v1.RelayReserveRequest.observed_at:type_name -> google.protobuf.Timestamp
	25, // 3: anytty.cloud.v1.RelayGrant.authorized_until:type_name -> google.protobuf.Timestamp
	6,  // 4: anytty.cloud.v1.RelayGrant.policy:type_name -> anytty.cloud.v1.RelayPolicySnapshot
	3,  // 5: anytty.cloud.v1.RelayReserveResponse.code:type_name -> anytty.cloud.v1.RelayResponseCode
	8,  // 6: anytty.cloud.v1.RelayReserveResponse.grant:type_name -> anytty.cloud.v1.RelayGrant
	13, // 7: anytty.cloud.v1.RelayReserveResponse.terminal:type_name -> anytty.cloud.v1.RelaySettlementAck
	26, // 8: anytty.cloud.v1.RelayReserveResponse.entitlement_failure:type_name -> anytty.cloud.v1.CloudEntitlementFailure
	25, // 9: anytty.cloud.v1.RelayRenewRequest.observed_at:type_name -> google.protobuf.Timestamp
	3,  // 10: anytty.cloud.v1.RelayRenewResponse.code:type_name -> anytty.cloud.v1.RelayResponseCode
	8,  // 11: anytty.cloud.v1.RelayRenewResponse.grant:type_name -> anytty.cloud.v1.RelayGrant
	13, // 12: anytty.cloud.v1.RelayRenewResponse.terminal:type_name -> anytty.cloud.v1.RelaySettlementAck
	26, // 13: anytty.cloud.v1.RelayRenewResponse.entitlement_failure:type_name -> anytty.cloud.v1.CloudEntitlementFailure
	2,  // 14: anytty.cloud.v1.RelaySettlement.kind:type_name -> anytty.cloud.v1.RelaySettlementKind
	25, // 15: anytty.cloud.v1.RelaySettlement.observed_at:type_name -> google.protobuf.Timestamp
	2,  // 16: anytty.cloud.v1.RelaySettlementAck.kind:type_name -> anytty.cloud.v1.RelaySettlementKind
	25, // 17: anytty.cloud.v1.RelaySettlementAck.observed_at:type_name -> google.protobuf.Timestamp
	25, // 18: anytty.cloud.v1.RelaySettlementAck.settled_at:type_name -> google.protobuf.Timestamp
	3,  // 19: anytty.cloud.v1.RelaySettlementAck.code:type_name -> anytty.cloud.v1.RelayResponseCode
	3,  // 20: anytty.cloud.v1.RelayQueryResponse.code:type_name -> anytty.cloud.v1.RelayResponseCode
	8,  // 21: anytty.cloud.v1.RelayQueryResponse.grant:type_name -> anytty.cloud.v1.RelayGrant
	13, // 22: anytty.cloud.v1.RelayQueryResponse.terminal:type_name -> anytty.cloud.v1.RelaySettlementAck
	26, // 23: anytty.cloud.v1.RelayQueryResponse.entitlement_failure:type_name -> anytty.cloud.v1.CloudEntitlementFailure
	25, // 24: anytty.cloud.v1.RelayRuntimePolicy.period_start:type_name -> google.protobuf.Timestamp
	25, // 25: anytty.cloud.v1.RelayRuntimePolicy.period_end:type_name -> google.protobuf.Timestamp
	25, // 26: anytty.cloud.v1.RelayAuthorizeRequest.observed_at:type_name -> google.protobuf.Timestamp
	16, // 27: anytty.cloud.v1.RelayAuthorizeResponse.policy:type_name -> anytty.cloud.v1.RelayRuntimePolicy
	26, // 28: anytty.cloud.v1.RelayAuthorizeResponse.entitlement_failure:type_name -> anytty.cloud.v1.CloudEntitlementFailure
	25, // 29: anytty.cloud.v1.RelayUsageSample.sampled_at:type_name -> google.protobuf.Timestamp
	19, // 30: anytty.cloud.v1.RelayUsageBatch.samples:type_name -> anytty.cloud.v1.RelayUsageSample
	4,  // 31: anytty.cloud.v1.RelayAccountAction.action:type_name -> anytty.cloud.v1.RelayAccountActionType
	25, // 32: anytty.cloud.v1.RelayAccountAction.period_start:type_name -> google.protobuf.Timestamp
	25, // 33: anytty.cloud.v1.RelayAccountAction.period_end:type_name -> google.protobuf.Timestamp
	21, // 34: anytty.cloud.v1.RelayUsageAck.actions:type_name -> anytty.cloud.v1.RelayAccountAction
	25, // 35: anytty.cloud.v1.RelayUsageAck.processed_at:type_name -> google.protobuf.Timestamp
	25, // 36: anytty.cloud.v1.RelayICEConfig.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 37: anytty.cloud.v1.RelayJournalRecord.stage:type_name -> anytty.cloud.v1.RelayJournalStage
	7,  // 38: anytty.cloud.v1.RelayJournalRecord.reserve_request:type_name -> anytty.cloud.v1.RelayReserveRequest
	8,  // 39: anytty.cloud.v1.RelayJournalRecord.grant:type_name -> anytty.cloud.v1.RelayGrant
	12, // 40: anytty.cloud.v1.RelayJournalRecord.settlement:type_name -> anytty.cloud.v1.RelaySettlement
	41, // [41:41] is the sub-list for method output_type
	41, // [41:41] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_cloud_v1_usage_proto_init() }
func file_cloud_v1_usage_proto_init() {
	if File_cloud_v1_usage_proto != nil {
		return
	}
	file_cloud_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cloud_v1_usage_proto_rawDesc), len(file_cloud_v1_usage_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cloud_v1_usage_proto_goTypes,
		DependencyIndexes: file_cloud_v1_usage_proto_depIdxs,
		EnumInfos:         file_cloud_v1_usage_proto_enumTypes,
		MessageInfos:      file_cloud_v1_usage_proto_msgTypes,
	}.Build()
	File_cloud_v1_usage_proto = out.File
	file_cloud_v1_usage_proto_goTypes = nil
	file_cloud_v1_usage_proto_depIdxs = nil
}
