// Package appcodegen regenerates the application command codegen outputs from
// proto/access/apipb/application_commands.csv. See scripts/generate_application_api.go
// for the CLI entry point.
package appcodegen

import (
	"encoding/csv"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
)

type commandSpec struct {
	CommandOneof     string
	ResultOneof      string
	ControllerMethod string
	Capability       string
	ValidatorGroup   string
	ResponseKind     string
	TerminalResponse bool
}

var (
	csvPath = filepath.Join("proto", "access", "apipb", "application_commands.csv")

	browserSpec = commandSpec{
		CommandOneof: "browser_proxy_open", ResultOneof: "browser_proxy_open",
		ControllerMethod: "BrowserProxyOpen", Capability: "API_CAPABILITY_BROWSER_PROXY",
		ValidatorGroup: "browser", ResponseKind: "value",
		TerminalResponse: true,
	}
)

// runtimeUnusedMethods are commands whose exported ApplicationSession wrapper is
// hand-written in application_session.go; the generated helper is unexported.
var runtimeUnusedMethods = map[string]string{
	"history_window":  "executeHistoryWindow",
	"event_subscribe": "executeEventSubscribe",
}

// File is one generated output, relative to the repository root.
type File struct {
	Path    string
	Content []byte
}

// Generate reconstructs all application API codegen outputs for root.
func Generate(root string) ([]File, error) {
	rows, err := readCSV(filepath.Join(root, csvPath))
	if err != nil {
		return nil, err
	}
	outputs := []struct {
		path    string
		content string
	}{
		{filepath.Join("api_mapping", "application_commands.gen.go"), generateMapping(rows)},
		{filepath.Join("access", "engine", "runtime", "application_commands.gen.go"), generateRuntime(rows)},
		{filepath.Join("access", "engine", "binding", "application_commands.gen.go"), generateBinding(rows)},
	}
	files := make([]File, 0, len(outputs))
	for _, output := range outputs {
		formatted, err := format.Source([]byte(output.content))
		if err != nil {
			return nil, fmt.Errorf("format %s: %w", output.path, err)
		}
		files = append(files, File{Path: output.path, Content: formatted})
	}
	return files, nil
}

func readCSV(path string) ([]commandSpec, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()
	reader := csv.NewReader(file)
	records, err := reader.ReadAll()
	if err != nil {
		return nil, err
	}
	specs := make([]commandSpec, 0, len(records))
	for index, record := range records {
		if index == 0 {
			continue
		}
		if len(record) != 7 {
			return nil, fmt.Errorf("row %d has %d columns, want 7", index+1, len(record))
		}
		specs = append(specs, commandSpec{
			CommandOneof:     strings.TrimSpace(record[0]),
			ResultOneof:      strings.TrimSpace(record[1]),
			ControllerMethod: strings.TrimSpace(record[2]),
			Capability:       strings.TrimSpace(record[3]),
			ValidatorGroup:   strings.TrimSpace(record[4]),
			ResponseKind:     strings.TrimSpace(record[5]),
			TerminalResponse: strings.TrimSpace(record[6]) == "true",
		})
	}
	return specs, nil
}

func (spec commandSpec) commandType() string  { return pascal(spec.CommandOneof) + "Command" }
func (spec commandSpec) wrapperType() string  { return "CommandEnvelope_" + pascal(spec.CommandOneof) }
func (spec commandSpec) wrapperField() string { return pascal(spec.CommandOneof) }
func (spec commandSpec) resultWrapper() string {
	return "ResultEnvelope_" + pascal(spec.ResultOneof)
}
func (spec commandSpec) resultField() string { return pascal(spec.ResultOneof) }
func (spec commandSpec) resultType() string {
	if spec.ResultOneof == "live_screen" {
		return "NativeScreenResult"
	}
	return pascal(spec.ResultOneof) + "Result"
}

func pascal(value string) string {
	parts := strings.Split(value, "_")
	var builder strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		builder.WriteString(strings.ToUpper(part[:1]))
		builder.WriteString(part[1:])
	}
	return builder.String()
}

func header(packageName string, imports string) string {
	return "// Code generated by scripts/generate_application_api.go; DO NOT EDIT.\n\npackage " +
		packageName + "\n\n" + imports
}

// generateMapping reproduces api_mapping/application_commands.gen.go.
func generateMapping(rows []commandSpec) string {
	ordered := make([]commandSpec, 0, len(rows)+1)
	ordered = append(ordered, rows...)
	ordered = append(ordered, browserSpec)

	var builder strings.Builder
	builder.WriteString(header("apimapping", "import \"github.com/anytty/anytty/proto/access/apipb\"\n"))
	builder.WriteString(`
// RequiredCapabilityForCommand returns the capability declared for a typed command.
func RequiredCapabilityForCommand(command *apipb.CommandEnvelope) apipb.ApiCapability {
	if command == nil {
		return apipb.ApiCapability_API_CAPABILITY_UNSPECIFIED
	}
	switch command.GetCommand().(type) {
`)
	for _, spec := range ordered {
		fmt.Fprintf(&builder, "\tcase *apipb.%s:\n\t\treturn apipb.ApiCapability_%s\n", spec.wrapperType(), spec.Capability)
	}
	builder.WriteString(`	default:
		return apipb.ApiCapability_API_CAPABILITY_UNSPECIFIED
	}
}
`)
	return builder.String()
}

func writeCaseList(builder *strings.Builder, rows []commandSpec) {
	for index, spec := range rows {
		if index == 0 {
			fmt.Fprintf(builder, "\tcase *apipb.%s", spec.wrapperType())
			continue
		}
		fmt.Fprintf(builder, ",\n\t\t*apipb.%s", spec.wrapperType())
	}
	if len(rows) > 0 {
		builder.WriteString(":\n")
	}
}

func generateRuntime(rows []commandSpec) string {
	ordered := make([]commandSpec, 0, len(rows)+1)
	for _, spec := range rows {
		ordered = append(ordered, spec)
		if spec.ValidatorGroup == "resource" {
			ordered = append(ordered, browserSpec)
		}
	}

	var builder strings.Builder
	builder.WriteString(header("runtime", `import (
	"context"

	"github.com/anytty/anytty/proto/access/apipb"
)
`))
	for _, spec := range ordered {
		method := runtimeUnusedMethods[spec.CommandOneof]
		if method == "" {
			method = spec.ControllerMethod
		}
		// 与 checked-in 输出一致：只有 browser_proxy_open 使用 ExecuteTerminal；
		// file/event/history 的 terminal-response 语义由 binding 层负责。
		executor := "Execute"
		if spec.CommandOneof == "browser_proxy_open" {
			executor = "ExecuteTerminal"
		}
		valueLike := spec.ResponseKind != "ack"
		fmt.Fprintf(&builder, "\n// %s executes the %s application command.\n", method, spec.CommandOneof)
		if valueLike {
			fmt.Fprintf(&builder, "func (session *ApplicationSession) %s(ctx context.Context, command *apipb.%s) (*apipb.%s, error) {\n", method, spec.commandType(), spec.resultType())
		} else {
			fmt.Fprintf(&builder, "func (session *ApplicationSession) %s(ctx context.Context, command *apipb.%s) error {\n", method, spec.commandType())
		}
		fmt.Fprintf(&builder, "\tresult, err := session.%s(ctx, &apipb.CommandEnvelope{Command: &apipb.%s{%s: command}})\n", executor, spec.wrapperType(), spec.wrapperField())
		if valueLike {
			builder.WriteString("\tif err != nil {\n\t\treturn nil, err\n\t}\n")
			fmt.Fprintf(&builder, "\tif result.Get%s() == nil {\n\t\treturn nil, missingApplicationResult(%q)\n\t}\n", spec.resultField(), spec.ResultOneof)
			fmt.Fprintf(&builder, "\treturn result.Get%s(), nil\n}\n", spec.resultField())
		} else {
			builder.WriteString("\tif err != nil {\n\t\treturn err\n\t}\n")
			builder.WriteString("\tif result.GetAcknowledge() == nil {\n\t\treturn missingApplicationResult(\"acknowledge\")\n\t}\n")
			builder.WriteString("\treturn nil\n}\n")
		}
	}
	return builder.String()
}

// generateBinding reproduces access/engine/binding/application_commands.gen.go.
func generateBinding(rows []commandSpec) string {
	terminalResponse := filter(rows, func(spec commandSpec) bool {
		return spec.TerminalResponse && spec.CommandOneof != "history_window"
	})
	var builder strings.Builder
	builder.WriteString(header("binding", "import \"github.com/anytty/anytty/proto/access/apipb\"\n"))
	builder.WriteString(`
// requiresTerminalResponse marks binding operations that own late-response resource cleanup.
func requiresTerminalResponse(command *apipb.CommandEnvelope) bool {
	if history := command.GetHistoryWindow(); history != nil {
		return history.GetMode() == apipb.HistoryWindowMode_HISTORY_WINDOW_MODE_UNSPECIFIED || history.GetMode() == apipb.HistoryWindowMode_HISTORY_WINDOW_MODE_LATEST
	}
	switch command.GetCommand().(type) {
`)
	writeCaseList(&builder, terminalResponse)
	builder.WriteString("\t\treturn true\n")
	builder.WriteString(`	default:
		return false
	}
}
`)
	return builder.String()
}

func filter(rows []commandSpec, keep func(commandSpec) bool) []commandSpec {
	out := make([]commandSpec, 0, len(rows))
	for _, row := range rows {
		if keep(row) {
			out = append(out, row)
		}
	}
	return out
}
